--ALTER  TABLE DBM.H_ORDREHODE ADD
--  TILBUD_SAAFROE     DECIMAL     (1,0)     NOT NULL WITH DEFAULT 0.0;
--ALTER  TABLE DBM.H_ORDRELINJER ADD
--  RESEPT             DECIMAL     (6,0)     NOT NULL WITH DEFAULT 0.0;
--ALTER  TABLE DBM.H_ORDRELINJER ADD
--  RESEPT_VERSJON     DECIMAL     (4,0)     NOT NULL WITH DEFAULT 0.0;
ALTER  TABLE DBM.KORRIGERINGER ADD
  VAREGR             DECIMAL     (6,0)     NOT NULL WITH DEFAULT 0.0;
