REM kj�rt 02.04.2023
set DB2INSTANCE=DB2HST
DB2 BACKUP DATABASE BASISHST ONLINE TO "G:\DB2HSTBACKUP" WITH 2 BUFFERS BUFFER 1024 PARALLELISM 1 COMPRESS  UTIL_IMPACT_PRIORITY 50 INCLUDE LOGS WITHOUT PROMPTING

