--
      DELETE
      FROM DBM.H_ORDREHODE H
      WHERE  (H.TILFAKTDATO = 0 AND DATE(H.TIDSPUNKT) < '1998-01-01');
      DELETE
      FROM DBM.H_ORDREHODE H
      WHERE  (H.TILFAKTDATO = 0 AND DATE(H.TIDSPUNKT) < '1998-02-01');
      DELETE
      FROM DBM.H_ORDREHODE H
      WHERE  (H.TILFAKTDATO = 0 AND DATE(H.TIDSPUNKT) < '1998-03-01');
      DELETE
      FROM DBM.H_ORDREHODE H
      WHERE  (H.TILFAKTDATO = 0 AND DATE(H.TIDSPUNKT) < '1998-04-01');
      DELETE
      FROM DBM.H_ORDREHODE H
      WHERE  (H.TILFAKTDATO = 0 AND DATE(H.TIDSPUNKT) < '1998-05-01');
      DELETE
      FROM DBM.H_ORDREHODE H
      WHERE  (H.TILFAKTDATO = 0 AND DATE(H.TIDSPUNKT) < '1998-06-01');
      DELETE
      FROM DBM.H_ORDREHODE H
      WHERE  (H.TILFAKTDATO = 0 AND DATE(H.TIDSPUNKT) < '1998-07-01');
      DELETE
      FROM DBM.H_ORDREHODE H
      WHERE  (H.TILFAKTDATO = 0 AND DATE(H.TIDSPUNKT) < '1998-08-01');
      DELETE
      FROM DBM.H_ORDREHODE H
      WHERE  (H.TILFAKTDATO = 0 AND DATE(H.TIDSPUNKT) < '1998-09-01');
      DELETE
      FROM DBM.H_ORDREHODE H
      WHERE  (H.TILFAKTDATO = 0 AND DATE(H.TIDSPUNKT) < '1998-10-01');
      DELETE
      FROM DBM.H_ORDREHODE H
      WHERE  (H.TILFAKTDATO = 0 AND DATE(H.TIDSPUNKT) < '1998-11-01');
      DELETE
      FROM DBM.H_ORDREHODE H
      WHERE  (H.TILFAKTDATO = 0 AND DATE(H.TIDSPUNKT) < '1998-12-01');
      DELETE
      FROM DBM.H_ORDREHODE H
      WHERE  (H.TILFAKTDATO = 0 AND DATE(H.TIDSPUNKT) < '1999-01-01');
//
//
//
      DELETE
      FROM DBM.H_ORDREHODE H
      WHERE  (H.TILFAKTDATO = 0 AND DATE(H.TIDSPUNKT) < '1997-01-01');
      DELETE
      FROM DBM.H_ORDREHODE H
      WHERE  (H.TILFAKTDATO = 0 AND DATE(H.TIDSPUNKT) < '1998-01-01');
      DELETE
      FROM DBM.H_ORDREHODE H
      WHERE  (H.TILFAKTDATO = 0 AND DATE(H.TIDSPUNKT) < '1999-01-01');
//
      SELECT COUNT(*)
      FROM DBM.H_ORDREHODE H
--    WHERE  (H.TILFAKTDATO > 0 AND H.TILFAKTDATO < 19990101)
      WHERE  (H.TILFAKTDATO = 0 AND DATE(H.TIDSPUNKT) < '1995-05-01');
//
      SELECT COUNT(*)
      FROM DBM.H_ORDREHODE H
--    WHERE  (H.TILFAKTDATO > 0 AND H.TILFAKTDATO < 19990101)
      WHERE  (H.TILFAKTDATO = 0 AND DATE(H.TIDSPUNKT) < '1999-01-01');
//
      SELECT COUNT(*)
      FROM DBM.H_ORDREHODE H
      WHERE ((H.TILFAKTDATO > 0 AND H.TILFAKTDATO < 19990101)
          OR (H.TILFAKTDATO = 0 AND DATE(H.TIDSPUNKT) < '1999-01-01'));
