-- KJØRES VHA. FKSQL.REX
  EXPORT TO K:\FKAVD\BASISHST\FKFAHEAD97.IXF OF IXF    SELECT * FROM P7910A1.FKFAHEAD97;
  EXPORT TO K:\FKAVD\BASISHST\FKFAHEAD98.IXF OF IXF    SELECT * FROM P7910A1.FKFAHEAD98;
  EXPORT TO K:\FKAVD\BASISHST\FKFAHEAD99.IXF OF IXF    SELECT * FROM P7910A1.FKFAHEAD99;
--
  EXPORT TO K:\FKAVD\BASISHST\FKFAVLIN97.IXF OF IXF    SELECT * FROM P7910A1.FKFAVLIN97;
  EXPORT TO K:\FKAVD\BASISHST\FKFAVLIN98.IXF OF IXF    SELECT * FROM P7910A1.FKFAVLIN98;
  EXPORT TO K:\FKAVD\BASISHST\FKFAVLIN99.IXF OF IXF    SELECT * FROM P7910A1.FKFAVLIN99;
--
  EXPORT TO K:\FKAVD\BASISHST\FKFAKOMM97.IXF OF IXF    SELECT * FROM P7910A1.FKFAKOMM97;
  EXPORT TO K:\FKAVD\BASISHST\FKFAKOMM98.IXF OF IXF    SELECT * FROM P7910A1.FKFAKOMM98;
  EXPORT TO K:\FKAVD\BASISHST\FKFAKOMM99.IXF OF IXF    SELECT * FROM P7910A1.FKFAKOMM99;
--
  EXPORT TO K:\FKAVD\BASISHST\FKFAUTLV97.IXF OF IXF    SELECT * FROM P7910A1.FKFAUTLV97;
  EXPORT TO K:\FKAVD\BASISHST\FKFAUTLV98.IXF OF IXF    SELECT * FROM P7910A1.FKFAUTLV98;
  EXPORT TO K:\FKAVD\BASISHST\FKFAUTLV99.IXF OF IXF    SELECT * FROM P7910A1.FKFAUTLV99;
--
  EXPORT TO K:\FKAVD\BASISHST\FKFAVAMO97.IXF OF IXF    SELECT * FROM P7910A1.FKFAVAMO97;
  EXPORT TO K:\FKAVD\BASISHST\FKFAVAMO98.IXF OF IXF    SELECT * FROM P7910A1.FKFAVAMO98;
  EXPORT TO K:\FKAVD\BASISHST\FKFAVAMO99.IXF OF IXF    SELECT * FROM P7910A1.FKFAVAMO99;
--
  EXPORT TO K:\FKAVD\BASISHST\FKFASAMF97.IXF OF IXF    SELECT * FROM P7910A1.FKFASAMF97;
  EXPORT TO K:\FKAVD\BASISHST\FKFASAMF98.IXF OF IXF    SELECT * FROM P7910A1.FKFASAMF98;
  EXPORT TO K:\FKAVD\BASISHST\FKFASAMF99.IXF OF IXF    SELECT * FROM P7910A1.FKFASAMF99;
