drop TABLE DBM.ORDRELINJER_VEI;
CREATE TABLE DBM.ORDRELINJER_VEI (
  aar                DECIMAL     (4,0)     NOT NULL WITH DEFAULT 0.0,
  AVDNR              DECIMAL     (6,0)     NOT NULL WITH DEFAULT 0.0,
  ORDRENR            DECIMAL     (6,0)     NOT NULL WITH DEFAULT 0.0,
  LINJENR            DECIMAL     (3,0)     NOT NULL WITH DEFAULT 0.0,
  VEIING_NR          DECIMAL     (3,0)     NOT NULL WITH DEFAULT 0.0,
  SILONR             DECIMAL     (6,0)     NOT NULL WITH DEFAULT 0.0,
  ROMNR              CHARACTER   (3)       NOT NULL WITH DEFAULT ' ',
  VEKT               DECIMAL     (11,2)    NOT NULL WITH DEFAULT 0.0,
  TIDSPUNKT_VB       TIMESTAMP             NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY(aar, AVDNR, ORDRENR, LINJENR, VEIING_NR)
  )   ;
CREATE INDEX DBM.ORDRELINJER_BVX1O  ON DBM.ORDRELINJER_VEI
  (TIDSPUNKT_VB );
//
-- KJØRES VHA. FKSQL.REX
-- TAR MED ORDRELINJER_VEI
-- EXPORTERER eldre enn 2007
  EXPORT TO K:\FKAVD\BASISHST\ORDRELIN_VEI.IXF OF IXF
       SELECT YEAR(H.TIDSPUNKT_VB), H.*
       FROM DBM.ORDRELINJER_VEI H
       where tidspunkt_VB < '2007-01-01-00.00.00.000000'
//
select count(*) from dbm.ordrelinjer_vei
where tidspunkt_VB > '2007-01-01-00.00.00.000000'
//
