--
--  UTTREKK DANNET FRA EXPOPTFIX1.DDL
--
  LOAD FROM \\SFKDC02\EDB\FKAVD\BASISHST\ORDREHFX1.IXF OF IXF INSERT INTO
       DBM.H_ORDREHODE      NONRECOVERABLE USING F:\DRLOAD;
  LOAD FROM \\SFKDC02\EDB\FKAVD\BASISHST\ORDRELFX1.IXF OF IXF INSERT INTO
       DBM.H_ORDRELINJER    NONRECOVERABLE USING F:\DRLOAD;
  LOAD FROM \\SFKDC02\EDB\FKAVD\BASISHST\ORDREMFX1.IXF OF IXF INSERT INTO
      DBM.H_ORDREMERKNAD    NONRECOVERABLE USING F:\DRLOAD;
