-- KJØRES VHA. FKSQL.REX
-- SAMMENLIGN TABELLENE I BASISPRO OG BASISHST FØRST FOR å SIKRE AT DE ER LIKE
--
--LOAD FROM \\FKHKBDC\EDB\FKAVD\BASISHST\HF_ORDREHODE00.IXF OF IXF INSERT INTO
--     DBM.H_FAKT_ORDREHODE      NONRECOVERABLE USING G:\DRLOAD;
  LOAD FROM \\FKHKBDC\EDB\FKAVD\BASISHST\HF_ORDREL00_12.IXF    OF IXF INSERT INTO
       DBM.H_FAKT_ORDRELINJER    NONRECOVERABLE USING G:\DRLOAD;
