#!/usr/bin/env pwsh

<#
.SYNOPSIS
    Compares "before" and "after" security settings captures to identify changes.

.DESCRIPTION
    This script compares the JSON files generated by Export-ServiceSecuritySettings.ps1
    to show what changed between the "before" and "after" snapshots.

.PARAMETER BeforeFile
    Path to the "before" UserRights.json file

.PARAMETER AfterFile
    Path to the "after" UserRights.json file

.PARAMETER Username
    Username to focus on in the comparison (optional)

.EXAMPLE
    .\Compare-SecurityCaptures.ps1
    # Automatically finds and compares the latest before/after captures

.EXAMPLE
    .\Compare-SecurityCaptures.ps1 -BeforeFile ".\SecurityDiagnostics\before_20231211_120000_UserRights.json" -AfterFile ".\SecurityDiagnostics\after_20231211_130000_UserRights.json"

.NOTES
    Author: Geir Helge Starholm, www.dEdge.no
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $false)]
    [string]$BeforeFile,
    
    [Parameter(Mandatory = $false)]
    [string]$AfterFile,
    
    [Parameter(Mandatory = $false)]
    [string]$Username
)

Import-Module GlobalFunctions -Force

try {
    $ErrorActionPreference = "Stop"
    
    Write-Host ""
    Write-Host "═══════════════════════════════════════════════════════════════" -ForegroundColor Cyan
    Write-Host "        Security Settings Comparison Tool" -ForegroundColor Cyan
    Write-Host "═══════════════════════════════════════════════════════════════" -ForegroundColor Cyan
    Write-Host ""
    
    $diagDir = "$PSScriptRoot\SecurityDiagnostics"
    
    if (-not (Test-Path $diagDir)) {
        Write-Host "❌ No diagnostics directory found: $diagDir" -ForegroundColor Red
        Write-Host "   Run Export-ServiceSecuritySettings.ps1 first!" -ForegroundColor Yellow
        exit 1
    }
    
    # Auto-detect files if not specified
    if (-not $BeforeFile) {
        # Look in BeforeServiceAdded folder first
        $beforeFolder = "$diagDir\BeforeServiceAdded"
        if (Test-Path $beforeFolder) {
            $beforeFiles = Get-ChildItem -Path $beforeFolder -Filter "*_UserRights.json" | Sort-Object LastWriteTime -Descending
            if ($beforeFiles) {
                $BeforeFile = $beforeFiles[0].FullName
                Write-Host "📂 Auto-detected BEFORE file: BeforeServiceAdded\$($beforeFiles[0].Name)" -ForegroundColor Green
            }
        }
        
        # Fallback to old naming convention
        if (-not $BeforeFile) {
            $beforeFiles = Get-ChildItem -Path $diagDir -Filter "before_*_UserRights.json" -Recurse | Sort-Object LastWriteTime -Descending
            if ($beforeFiles) {
                $BeforeFile = $beforeFiles[0].FullName
                Write-Host "📂 Auto-detected BEFORE file: $($beforeFiles[0].Name)" -ForegroundColor Green
            }
        }
        
        if (-not $BeforeFile) {
            Write-Host "❌ No 'BeforeServiceAdded' capture found in $diagDir" -ForegroundColor Red
            exit 1
        }
    }
    
    if (-not $AfterFile) {
        # Look in AfterServiceFail first, then AfterServiceOk
        $afterFolders = @("$diagDir\AfterServiceFail", "$diagDir\AfterServiceOk")
        
        foreach ($afterFolder in $afterFolders) {
            if (Test-Path $afterFolder) {
                $afterFiles = Get-ChildItem -Path $afterFolder -Filter "*_UserRights.json" | Sort-Object LastWriteTime -Descending
                if ($afterFiles) {
                    $AfterFile = $afterFiles[0].FullName
                    $folderName = Split-Path $afterFolder -Leaf
                    Write-Host "📂 Auto-detected AFTER file: $folderName\$($afterFiles[0].Name)" -ForegroundColor Green
                    break
                }
            }
        }
        
        # Fallback to old naming convention
        if (-not $AfterFile) {
            $afterFiles = Get-ChildItem -Path $diagDir -Filter "after_*_UserRights.json" -Recurse | Sort-Object LastWriteTime -Descending
            if ($afterFiles) {
                $AfterFile = $afterFiles[0].FullName
                Write-Host "📂 Auto-detected AFTER file: $($afterFiles[0].Name)" -ForegroundColor Green
            }
        }
        
        if (-not $AfterFile) {
            Write-Host "❌ No 'AfterServiceFail' or 'AfterServiceOk' capture found in $diagDir" -ForegroundColor Red
            exit 1
        }
    }
    
    Write-Host ""
    
    # Load files
    $beforeData = Get-Content -Path $BeforeFile -Raw | ConvertFrom-Json
    $afterData = Get-Content -Path $AfterFile -Raw | ConvertFrom-Json
    
    Write-Host "📊 Comparing user rights assignments..." -ForegroundColor Cyan
    Write-Host ""
    
    # Get all unique rights
    $allRights = @()
    $allRights += $beforeData.PSObject.Properties.Name
    $allRights += $afterData.PSObject.Properties.Name
    $allRights = $allRights | Select-Object -Unique | Sort-Object
    
    $changes = @()
    
    foreach ($right in $allRights) {
        $beforeValue = if ($beforeData.PSObject.Properties[$right]) { $beforeData.$right } else { $null }
        $afterValue = if ($afterData.PSObject.Properties[$right]) { $afterData.$right } else { $null }
        
        if ($beforeValue -ne $afterValue) {
            $change = [PSCustomObject]@{
                Right = $right
                Before = $beforeValue
                After = $afterValue
                Status = if ($afterValue -and -not $beforeValue) { "ADDED" } 
                        elseif ($beforeValue -and -not $afterValue) { "REMOVED" } 
                        else { "CHANGED" }
            }
            $changes += $change
            
            $color = switch ($change.Status) {
                "ADDED" { "Green" }
                "REMOVED" { "Red" }
                "CHANGED" { "Yellow" }
            }
            
            Write-Host "[$($change.Status)] $right" -ForegroundColor $color
            Write-Host "   Before: $beforeValue" -ForegroundColor Gray
            Write-Host "   After:  $afterValue" -ForegroundColor Gray
            Write-Host ""
        }
    }
    
    if ($changes.Count -eq 0) {
        Write-Host "✅ No changes detected in user rights assignments" -ForegroundColor Green
    }
    else {
        Write-Host "📋 Summary: $($changes.Count) rights changed" -ForegroundColor Yellow
    }
    
    Write-Host ""
    Write-Host "═══════════════════════════════════════════════════════════════" -ForegroundColor Cyan
    
    # If username specified, check if it's in the rights
    if ($Username) {
        Write-Host ""
        Write-Host "🔍 Checking rights for user: $Username" -ForegroundColor Cyan
        
        try {
            $ntAccount = New-Object System.Security.Principal.NTAccount($Username)
            $userSid = $ntAccount.Translate([System.Security.Principal.SecurityIdentifier])
            $userSidString = $userSid.Value
            
            Write-Host "   SID: $userSidString" -ForegroundColor Gray
            Write-Host ""
            
            $userHasRights = @()
            foreach ($right in $allRights) {
                $afterValue = if ($afterData.PSObject.Properties[$right]) { $afterData.$right } else { "" }
                if ($afterValue -match [regex]::Escape($userSidString)) {
                    $userHasRights += $right
                    Write-Host "   ✅ $right" -ForegroundColor Green
                }
            }
            
            if ($userHasRights.Count -eq 0) {
                Write-Host "   ⚠️  User has no special rights assigned" -ForegroundColor Yellow
            }
        }
        catch {
            Write-Host "   ❌ Failed to resolve username: $($_.Exception.Message)" -ForegroundColor Red
        }
    }
    
    Write-Host ""
}
catch {
    Write-Host ""
    Write-Host "❌ ERROR: $($_.Exception.Message)" -ForegroundColor Red
    exit 1
}

