namespace ServerMonitor.Core.Models;

/// <summary>
/// Represents an alert generated by the monitoring system
/// </summary>
public class Alert
{
    /// <summary>
    /// Unique identifier for the alert
    /// </summary>
    public Guid Id { get; init; } = Guid.NewGuid();

    /// <summary>
    /// Severity level of the alert
    /// </summary>
    public AlertSeverity Severity { get; init; }

    /// <summary>
    /// Category that generated the alert
    /// </summary>
    public string Category { get; init; } = string.Empty;

    /// <summary>
    /// Alert message
    /// </summary>
    public string Message { get; init; } = string.Empty;

    /// <summary>
    /// Detailed description
    /// </summary>
    public string? Details { get; init; }

    /// <summary>
    /// Timestamp when alert was generated
    /// </summary>
    public DateTime Timestamp { get; init; } = DateTime.UtcNow;

    /// <summary>
    /// Server name where alert originated
    /// </summary>
    public string ServerName { get; init; } = Environment.MachineName;

    /// <summary>
    /// Additional metadata
    /// </summary>
    public Dictionary<string, object> Metadata { get; init; } = new();

    /// <summary>
    /// Distribution history - tracks where this alert was sent
    /// </summary>
    public List<AlertDistribution> DistributionHistory { get; set; } = new();

    /// <summary>
    /// List of channel types to suppress for this alert (e.g., ["SMS", "Email"]).
    /// Channel types must match the Type in Alerting.Channels (SMS, Email, EventLog, File, WKMonitor).
    /// If null or empty, all enabled channels will be used (default behavior).
    /// </summary>
    public List<string> SuppressedChannels { get; init; } = new();
}

/// <summary>
/// Records where an alert was distributed
/// </summary>
public class AlertDistribution
{
    /// <summary>
    /// Channel type (SMS, Email, WKMonitor, EventLog, File)
    /// </summary>
    public string ChannelType { get; init; } = string.Empty;

    /// <summary>
    /// Distribution timestamp
    /// </summary>
    public DateTime Timestamp { get; init; } = DateTime.UtcNow;

    /// <summary>
    /// Destination address (phone number, email, file path, etc.)
    /// </summary>
    public string Destination { get; init; } = string.Empty;

    /// <summary>
    /// Success status
    /// </summary>
    public bool Success { get; init; }

    /// <summary>
    /// Error message if failed
    /// </summary>
    public string? ErrorMessage { get; init; }
}

/// <summary>
/// Alert severity levels
/// </summary>
public enum AlertSeverity
{
    Informational = 0,
    Warning = 1,
    Critical = 2
}

