CONNECT TO FKMPRD user db2nt using ntdb2;
  LOAD  FROM F:\DRLOAD\DBBKORR.DEL
   OF DEL
   MESSAGES LOADBHKORR.MSG REMOTE FILE F:\DRLOAD\BHKORR
   REPLACE INTO DBM.BEHOLD_KORR STATISTICS YES AND INDEXES ALL
   NONRECOVERABLE USING F:\DRLOAD;
