SQL3109N  Hjelperutinen begynner å laste inn data fra filen 
"F:\DRLOAD\DBBKORR.DEL".

SQL3500W  Funksjonen starter fasen "LOAD" på klokkeslettet "31.10.2025 
21.40.34.134518".

SQL3519W  Start innlasting av konsistenspunkt. Antall inndataposter = "0".

SQL3520W  Innlastingen av konsistenspunkt var vellykket.

SQL3535W  Det er ikke lenger støtte for parameteren "USING" for 
LOAD-kommandoen.  Verdien blir oversett av innlastingsfunksjonen.

SQL3110N  Funksjonen er ferdig med behandlingen. Det ble lest "2971636" rader 
fra inndatafilen.

SQL3519W  Start innlasting av konsistenspunkt. Antall inndataposter = 
"2971636".

SQL3520W  Innlastingen av konsistenspunkt var vellykket.

SQL3515W  Funksjonen avsluttet fasen "LOAD" på klokkeslettet "31.10.2025 
21.40.43.584360".

SQL3500W  Funksjonen starter fasen "BUILD" på klokkeslettet "31.10.2025 
21.40.43.590698".

SQL3213I  Indekseringsmodusen er "REBUILD".

SQL3515W  Funksjonen avsluttet fasen "BUILD" på klokkeslettet "31.10.2025 
21.40.45.631950".


Antall leste rader          = 2971636
Antall utelatte rader       = 0
Antall innlastede rader     = 2971636
Antall avviste rader        = 0
Antall slettede rader       = 0
Antall iverksatte rader     = 2971636

SQL3109N  Hjelperutinen begynner å laste inn data fra filen 
"F:\DRLOAD\DBBKORR.DEL".

SQL3500W  Funksjonen starter fasen "LOAD" på klokkeslettet "01.11.2025 
16.42.19.389534".

SQL3519W  Start innlasting av konsistenspunkt. Antall inndataposter = "0".

SQL3520W  Innlastingen av konsistenspunkt var vellykket.

SQL3535W  Det er ikke lenger støtte for parameteren "USING" for 
LOAD-kommandoen.  Verdien blir oversett av innlastingsfunksjonen.

SQL3110N  Funksjonen er ferdig med behandlingen. Det ble lest "2973083" rader 
fra inndatafilen.

SQL3519W  Start innlasting av konsistenspunkt. Antall inndataposter = 
"2973083".

SQL3520W  Innlastingen av konsistenspunkt var vellykket.

SQL3515W  Funksjonen avsluttet fasen "LOAD" på klokkeslettet "01.11.2025 
16.42.27.867604".

SQL3500W  Funksjonen starter fasen "BUILD" på klokkeslettet "01.11.2025 
16.42.27.875226".

SQL3213I  Indekseringsmodusen er "REBUILD".

SQL3515W  Funksjonen avsluttet fasen "BUILD" på klokkeslettet "01.11.2025 
16.42.29.760871".


Antall leste rader          = 2973083
Antall utelatte rader       = 0
Antall innlastede rader     = 2973083
Antall avviste rader        = 0
Antall slettede rader       = 0
Antall iverksatte rader     = 2973083

SQL3109N  Hjelperutinen begynner å laste inn data fra filen 
"F:\DRLOAD\DBBKORR.DEL".

SQL3500W  Funksjonen starter fasen "LOAD" på klokkeslettet "08.11.2025 
17.47.52.554677".

SQL3519W  Start innlasting av konsistenspunkt. Antall inndataposter = "0".

SQL3520W  Innlastingen av konsistenspunkt var vellykket.

SQL3535W  Det er ikke lenger støtte for parameteren "USING" for 
LOAD-kommandoen.  Verdien blir oversett av innlastingsfunksjonen.

SQL3110N  Funksjonen er ferdig med behandlingen. Det ble lest "2986186" rader 
fra inndatafilen.

SQL3519W  Start innlasting av konsistenspunkt. Antall inndataposter = 
"2986186".

SQL3520W  Innlastingen av konsistenspunkt var vellykket.

SQL3515W  Funksjonen avsluttet fasen "LOAD" på klokkeslettet "08.11.2025 
17.48.00.846404".

SQL3500W  Funksjonen starter fasen "BUILD" på klokkeslettet "08.11.2025 
17.48.00.852789".

SQL3213I  Indekseringsmodusen er "REBUILD".

SQL3515W  Funksjonen avsluttet fasen "BUILD" på klokkeslettet "08.11.2025 
17.48.02.716943".


Antall leste rader          = 2986186
Antall utelatte rader       = 0
Antall innlastede rader     = 2986186
Antall avviste rader        = 0
Antall slettede rader       = 0
Antall iverksatte rader     = 2986186

SQL3109N  Hjelperutinen begynner å laste inn data fra filen 
"F:\DRLOAD\DBBKORR.DEL".

SQL3500W  Funksjonen starter fasen "LOAD" på klokkeslettet "15.11.2025 
18.24.30.325196".

SQL3519W  Start innlasting av konsistenspunkt. Antall inndataposter = "0".

SQL3520W  Innlastingen av konsistenspunkt var vellykket.

SQL3535W  Det er ikke lenger støtte for parameteren "USING" for 
LOAD-kommandoen.  Verdien blir oversett av innlastingsfunksjonen.

SQL3110N  Funksjonen er ferdig med behandlingen. Det ble lest "3001661" rader 
fra inndatafilen.

SQL3519W  Start innlasting av konsistenspunkt. Antall inndataposter = 
"3001661".

SQL3520W  Innlastingen av konsistenspunkt var vellykket.

SQL3515W  Funksjonen avsluttet fasen "LOAD" på klokkeslettet "15.11.2025 
18.24.38.533621".

SQL3500W  Funksjonen starter fasen "BUILD" på klokkeslettet "15.11.2025 
18.24.38.539903".

SQL3213I  Indekseringsmodusen er "REBUILD".

SQL3515W  Funksjonen avsluttet fasen "BUILD" på klokkeslettet "15.11.2025 
18.24.40.414946".


Antall leste rader          = 3001661
Antall utelatte rader       = 0
Antall innlastede rader     = 3001661
Antall avviste rader        = 0
Antall slettede rader       = 0
Antall iverksatte rader     = 3001661

SQL3109N  Hjelperutinen begynner å laste inn data fra filen 
"F:\DRLOAD\DBBKORR.DEL".

SQL3500W  Funksjonen starter fasen "LOAD" på klokkeslettet "22.11.2025 
16.37.51.068190".

SQL3519W  Start innlasting av konsistenspunkt. Antall inndataposter = "0".

SQL3520W  Innlastingen av konsistenspunkt var vellykket.

SQL3535W  Det er ikke lenger støtte for parameteren "USING" for 
LOAD-kommandoen.  Verdien blir oversett av innlastingsfunksjonen.

SQL3110N  Funksjonen er ferdig med behandlingen. Det ble lest "3013400" rader 
fra inndatafilen.

SQL3519W  Start innlasting av konsistenspunkt. Antall inndataposter = 
"3013400".

SQL3520W  Innlastingen av konsistenspunkt var vellykket.

SQL3515W  Funksjonen avsluttet fasen "LOAD" på klokkeslettet "22.11.2025 
16.38.01.207667".

SQL3500W  Funksjonen starter fasen "BUILD" på klokkeslettet "22.11.2025 
16.38.01.213619".

SQL3213I  Indekseringsmodusen er "REBUILD".

SQL3515W  Funksjonen avsluttet fasen "BUILD" på klokkeslettet "22.11.2025 
16.38.03.666448".


Antall leste rader          = 3013400
Antall utelatte rader       = 0
Antall innlastede rader     = 3013400
Antall avviste rader        = 0
Antall slettede rader       = 0
Antall iverksatte rader     = 3013400

SQL3109N  Hjelperutinen begynner å laste inn data fra filen 
"F:\DRLOAD\DBBKORR.DEL".

SQL3500W  Funksjonen starter fasen "LOAD" på klokkeslettet "30.11.2025 
18.13.32.799342".

SQL3519W  Start innlasting av konsistenspunkt. Antall inndataposter = "0".

SQL3520W  Innlastingen av konsistenspunkt var vellykket.

SQL3535W  Det er ikke lenger støtte for parameteren "USING" for 
LOAD-kommandoen.  Verdien blir oversett av innlastingsfunksjonen.

SQL3110N  Funksjonen er ferdig med behandlingen. Det ble lest "3025873" rader 
fra inndatafilen.

SQL3519W  Start innlasting av konsistenspunkt. Antall inndataposter = 
"3025873".

SQL3520W  Innlastingen av konsistenspunkt var vellykket.

SQL3515W  Funksjonen avsluttet fasen "LOAD" på klokkeslettet "30.11.2025 
18.13.41.480017".

SQL3500W  Funksjonen starter fasen "BUILD" på klokkeslettet "30.11.2025 
18.13.41.486564".

SQL3213I  Indekseringsmodusen er "REBUILD".

SQL3515W  Funksjonen avsluttet fasen "BUILD" på klokkeslettet "30.11.2025 
18.13.43.344635".


Antall leste rader          = 3025873
Antall utelatte rader       = 0
Antall innlastede rader     = 3025873
Antall avviste rader        = 0
Antall slettede rader       = 0
Antall iverksatte rader     = 3025873

SQL3109N  Hjelperutinen begynner å laste inn data fra filen 
"F:\DRLOAD\DBBKORR.DEL".

SQL3500W  Funksjonen starter fasen "LOAD" på klokkeslettet "06.12.2025 
17.29.39.892683".

SQL3519W  Start innlasting av konsistenspunkt. Antall inndataposter = "0".

SQL3520W  Innlastingen av konsistenspunkt var vellykket.

SQL3535W  Det er ikke lenger støtte for parameteren "USING" for 
LOAD-kommandoen.  Verdien blir oversett av innlastingsfunksjonen.

SQL3110N  Funksjonen er ferdig med behandlingen. Det ble lest "3038437" rader 
fra inndatafilen.

SQL3519W  Start innlasting av konsistenspunkt. Antall inndataposter = 
"3038437".

SQL3520W  Innlastingen av konsistenspunkt var vellykket.

SQL3515W  Funksjonen avsluttet fasen "LOAD" på klokkeslettet "06.12.2025 
17.29.48.721922".

SQL3500W  Funksjonen starter fasen "BUILD" på klokkeslettet "06.12.2025 
17.29.48.729363".

SQL3213I  Indekseringsmodusen er "REBUILD".

SQL3515W  Funksjonen avsluttet fasen "BUILD" på klokkeslettet "06.12.2025 
17.29.51.716680".


Antall leste rader          = 3038437
Antall utelatte rader       = 0
Antall innlastede rader     = 3038437
Antall avviste rader        = 0
Antall slettede rader       = 0
Antall iverksatte rader     = 3038437

SQL3109N  Hjelperutinen begynner å laste inn data fra filen 
"F:\DRLOAD\DBBKORR.DEL".

SQL3500W  Funksjonen starter fasen "LOAD" på klokkeslettet "13.12.2025 
19.47.49.620027".

SQL3519W  Start innlasting av konsistenspunkt. Antall inndataposter = "0".

SQL3520W  Innlastingen av konsistenspunkt var vellykket.

SQL3535W  Det er ikke lenger støtte for parameteren "USING" for 
LOAD-kommandoen.  Verdien blir oversett av innlastingsfunksjonen.

SQL3110N  Funksjonen er ferdig med behandlingen. Det ble lest "3051441" rader 
fra inndatafilen.

SQL3519W  Start innlasting av konsistenspunkt. Antall inndataposter = 
"3051441".

SQL3520W  Innlastingen av konsistenspunkt var vellykket.

SQL3515W  Funksjonen avsluttet fasen "LOAD" på klokkeslettet "13.12.2025 
19.48.00.404115".

SQL3500W  Funksjonen starter fasen "BUILD" på klokkeslettet "13.12.2025 
19.48.00.409661".

SQL3213I  Indekseringsmodusen er "REBUILD".

SQL3515W  Funksjonen avsluttet fasen "BUILD" på klokkeslettet "13.12.2025 
19.48.02.744676".


Antall leste rader          = 3051441
Antall utelatte rader       = 0
Antall innlastede rader     = 3051441
Antall avviste rader        = 0
Antall slettede rader       = 0
Antall iverksatte rader     = 3051441

SQL3109N  Hjelperutinen begynner å laste inn data fra filen 
"F:\DRLOAD\DBBKORR.DEL".

SQL3500W  Funksjonen starter fasen "LOAD" på klokkeslettet "21.12.2025 
21.48.12.737604".

SQL3519W  Start innlasting av konsistenspunkt. Antall inndataposter = "0".

SQL3520W  Innlastingen av konsistenspunkt var vellykket.

SQL3535W  Det er ikke lenger støtte for parameteren "USING" for 
LOAD-kommandoen.  Verdien blir oversett av innlastingsfunksjonen.

SQL3110N  Funksjonen er ferdig med behandlingen. Det ble lest "3067485" rader 
fra inndatafilen.

SQL3519W  Start innlasting av konsistenspunkt. Antall inndataposter = 
"3067485".

SQL3520W  Innlastingen av konsistenspunkt var vellykket.

SQL3515W  Funksjonen avsluttet fasen "LOAD" på klokkeslettet "21.12.2025 
21.48.22.251276".

SQL3500W  Funksjonen starter fasen "BUILD" på klokkeslettet "21.12.2025 
21.48.22.257208".

SQL3213I  Indekseringsmodusen er "REBUILD".

SQL3515W  Funksjonen avsluttet fasen "BUILD" på klokkeslettet "21.12.2025 
21.48.24.956359".


Antall leste rader          = 3067485
Antall utelatte rader       = 0
Antall innlastede rader     = 3067485
Antall avviste rader        = 0
Antall slettede rader       = 0
Antall iverksatte rader     = 3067485

SQL3109N  Hjelperutinen begynner å laste inn data fra filen 
"F:\DRLOAD\DBBKORR.DEL".

SQL3500W  Funksjonen starter fasen "LOAD" på klokkeslettet "27.12.2025 
16.15.54.929497".

SQL3519W  Start innlasting av konsistenspunkt. Antall inndataposter = "0".

SQL3520W  Innlastingen av konsistenspunkt var vellykket.

SQL3535W  Det er ikke lenger støtte for parameteren "USING" for 
LOAD-kommandoen.  Verdien blir oversett av innlastingsfunksjonen.

SQL3110N  Funksjonen er ferdig med behandlingen. Det ble lest "3075408" rader 
fra inndatafilen.

SQL3519W  Start innlasting av konsistenspunkt. Antall inndataposter = 
"3075408".

SQL3520W  Innlastingen av konsistenspunkt var vellykket.

SQL3515W  Funksjonen avsluttet fasen "LOAD" på klokkeslettet "27.12.2025 
16.16.03.780222".

SQL3500W  Funksjonen starter fasen "BUILD" på klokkeslettet "27.12.2025 
16.16.03.786276".

SQL3213I  Indekseringsmodusen er "REBUILD".

SQL3515W  Funksjonen avsluttet fasen "BUILD" på klokkeslettet "27.12.2025 
16.16.05.806120".


Antall leste rader          = 3075408
Antall utelatte rader       = 0
Antall innlastede rader     = 3075408
Antall avviste rader        = 0
Antall slettede rader       = 0
Antall iverksatte rader     = 3075408

SQL3109N  Hjelperutinen begynner å laste inn data fra filen 
"F:\DRLOAD\DBBKORR.DEL".

SQL3500W  Funksjonen starter fasen "LOAD" på klokkeslettet "31.12.2025 
20.27.02.188356".

SQL3519W  Start innlasting av konsistenspunkt. Antall inndataposter = "0".

SQL3520W  Innlastingen av konsistenspunkt var vellykket.

SQL3535W  Det er ikke lenger støtte for parameteren "USING" for 
LOAD-kommandoen.  Verdien blir oversett av innlastingsfunksjonen.

SQL3110N  Funksjonen er ferdig med behandlingen. Det ble lest "3080829" rader 
fra inndatafilen.

SQL3519W  Start innlasting av konsistenspunkt. Antall inndataposter = 
"3080829".

SQL3520W  Innlastingen av konsistenspunkt var vellykket.

SQL3515W  Funksjonen avsluttet fasen "LOAD" på klokkeslettet "31.12.2025 
20.27.11.575053".

SQL3500W  Funksjonen starter fasen "BUILD" på klokkeslettet "31.12.2025 
20.27.11.581579".

SQL3213I  Indekseringsmodusen er "REBUILD".

SQL3515W  Funksjonen avsluttet fasen "BUILD" på klokkeslettet "31.12.2025 
20.27.13.553309".


Antall leste rader          = 3080829
Antall utelatte rader       = 0
Antall innlastede rader     = 3080829
Antall avviste rader        = 0
Antall slettede rader       = 0
Antall iverksatte rader     = 3080829

SQL3109N  Hjelperutinen begynner å laste inn data fra filen 
"F:\DRLOAD\DBBKORR.DEL".

SQL3500W  Funksjonen starter fasen "LOAD" på klokkeslettet "03.01.2026 
16.27.06.336040".

SQL3519W  Start innlasting av konsistenspunkt. Antall inndataposter = "0".

SQL3520W  Innlastingen av konsistenspunkt var vellykket.

SQL3535W  Det er ikke lenger støtte for parameteren "USING" for 
LOAD-kommandoen.  Verdien blir oversett av innlastingsfunksjonen.

SQL3110N  Funksjonen er ferdig med behandlingen. Det ble lest "2020211" rader 
fra inndatafilen.

SQL3519W  Start innlasting av konsistenspunkt. Antall inndataposter = 
"2020211".

SQL3520W  Innlastingen av konsistenspunkt var vellykket.

SQL3515W  Funksjonen avsluttet fasen "LOAD" på klokkeslettet "03.01.2026 
16.27.12.137867".

SQL3500W  Funksjonen starter fasen "BUILD" på klokkeslettet "03.01.2026 
16.27.12.145479".

SQL3213I  Indekseringsmodusen er "REBUILD".

SQL3515W  Funksjonen avsluttet fasen "BUILD" på klokkeslettet "03.01.2026 
16.27.13.545891".


Antall leste rader          = 2020211
Antall utelatte rader       = 0
Antall innlastede rader     = 2020211
Antall avviste rader        = 0
Antall slettede rader       = 0
Antall iverksatte rader     = 2020211

SQL3109N  Hjelperutinen begynner å laste inn data fra filen 
"F:\DRLOAD\DBBKORR.DEL".

SQL3500W  Funksjonen starter fasen "LOAD" på klokkeslettet "10.01.2026 
16.08.41.771500".

SQL3519W  Start innlasting av konsistenspunkt. Antall inndataposter = "0".

SQL3520W  Innlastingen av konsistenspunkt var vellykket.

SQL3535W  Det er ikke lenger støtte for parameteren "USING" for 
LOAD-kommandoen.  Verdien blir oversett av innlastingsfunksjonen.

SQL3110N  Funksjonen er ferdig med behandlingen. Det ble lest "2032868" rader 
fra inndatafilen.

SQL3519W  Start innlasting av konsistenspunkt. Antall inndataposter = 
"2032868".

SQL3520W  Innlastingen av konsistenspunkt var vellykket.

SQL3515W  Funksjonen avsluttet fasen "LOAD" på klokkeslettet "10.01.2026 
16.08.47.523863".

SQL3500W  Funksjonen starter fasen "BUILD" på klokkeslettet "10.01.2026 
16.08.47.529851".

SQL3213I  Indekseringsmodusen er "REBUILD".

SQL3515W  Funksjonen avsluttet fasen "BUILD" på klokkeslettet "10.01.2026 
16.08.49.090378".


Antall leste rader          = 2032868
Antall utelatte rader       = 0
Antall innlastede rader     = 2032868
Antall avviste rader        = 0
Antall slettede rader       = 0
Antall iverksatte rader     = 2032868

SQL3109N  Hjelperutinen begynner å laste inn data fra filen 
"F:\DRLOAD\DBBKORR.DEL".

SQL3500W  Funksjonen starter fasen "LOAD" på klokkeslettet "17.01.2026 
16.33.21.134779".

SQL3519W  Start innlasting av konsistenspunkt. Antall inndataposter = "0".

SQL3520W  Innlastingen av konsistenspunkt var vellykket.

SQL3535W  Det er ikke lenger støtte for parameteren "USING" for 
LOAD-kommandoen.  Verdien blir oversett av innlastingsfunksjonen.

SQL3110N  Funksjonen er ferdig med behandlingen. Det ble lest "2048119" rader 
fra inndatafilen.

SQL3519W  Start innlasting av konsistenspunkt. Antall inndataposter = 
"2048119".

SQL3520W  Innlastingen av konsistenspunkt var vellykket.

SQL3515W  Funksjonen avsluttet fasen "LOAD" på klokkeslettet "17.01.2026 
16.33.39.061690".

SQL3500W  Funksjonen starter fasen "BUILD" på klokkeslettet "17.01.2026 
16.33.39.069308".

SQL3213I  Indekseringsmodusen er "REBUILD".

SQL3515W  Funksjonen avsluttet fasen "BUILD" på klokkeslettet "17.01.2026 
16.33.40.521120".


Antall leste rader          = 2048119
Antall utelatte rader       = 0
Antall innlastede rader     = 2048119
Antall avviste rader        = 0
Antall slettede rader       = 0
Antall iverksatte rader     = 2048119

SQL3109N  Hjelperutinen begynner å laste inn data fra filen 
"F:\DRLOAD\DBBKORR.DEL".

SQL3500W  Funksjonen starter fasen "LOAD" på klokkeslettet "24.01.2026 
17.29.44.016331".

SQL3519W  Start innlasting av konsistenspunkt. Antall inndataposter = "0".

SQL3520W  Innlastingen av konsistenspunkt var vellykket.

SQL3535W  Det er ikke lenger støtte for parameteren "USING" for 
LOAD-kommandoen.  Verdien blir oversett av innlastingsfunksjonen.

SQL3110N  Funksjonen er ferdig med behandlingen. Det ble lest "2062179" rader 
fra inndatafilen.

SQL3519W  Start innlasting av konsistenspunkt. Antall inndataposter = 
"2062179".

SQL3520W  Innlastingen av konsistenspunkt var vellykket.

SQL3515W  Funksjonen avsluttet fasen "LOAD" på klokkeslettet "24.01.2026 
17.30.00.907962".

SQL3500W  Funksjonen starter fasen "BUILD" på klokkeslettet "24.01.2026 
17.30.03.924188".

SQL3213I  Indekseringsmodusen er "REBUILD".

SQL3515W  Funksjonen avsluttet fasen "BUILD" på klokkeslettet "24.01.2026 
17.30.05.359073".


Antall leste rader          = 2062179
Antall utelatte rader       = 0
Antall innlastede rader     = 2062179
Antall avviste rader        = 0
Antall slettede rader       = 0
Antall iverksatte rader     = 2062179

SQL3109N  Hjelperutinen begynner å laste inn data fra filen 
"F:\DRLOAD\DBBKORR.DEL".

SQL3500W  Funksjonen starter fasen "LOAD" på klokkeslettet "31.01.2026 
20.10.43.193519".

SQL3519W  Start innlasting av konsistenspunkt. Antall inndataposter = "0".

SQL3520W  Innlastingen av konsistenspunkt var vellykket.

SQL3535W  Det er ikke lenger støtte for parameteren "USING" for 
LOAD-kommandoen.  Verdien blir oversett av innlastingsfunksjonen.

SQL3110N  Funksjonen er ferdig med behandlingen. Det ble lest "2075985" rader 
fra inndatafilen.

SQL3519W  Start innlasting av konsistenspunkt. Antall inndataposter = 
"2075985".

SQL3520W  Innlastingen av konsistenspunkt var vellykket.

SQL3515W  Funksjonen avsluttet fasen "LOAD" på klokkeslettet "31.01.2026 
20.11.02.216178".

SQL3500W  Funksjonen starter fasen "BUILD" på klokkeslettet "31.01.2026 
20.11.02.222885".

SQL3213I  Indekseringsmodusen er "REBUILD".

SQL3515W  Funksjonen avsluttet fasen "BUILD" på klokkeslettet "31.01.2026 
20.11.04.530841".


Antall leste rader          = 2075985
Antall utelatte rader       = 0
Antall innlastede rader     = 2075985
Antall avviste rader        = 0
Antall slettede rader       = 0
Antall iverksatte rader     = 2075985

SQL3109N  Hjelperutinen begynner å laste inn data fra filen 
"F:\DRLOAD\DBBKORR.DEL".

SQL3500W  Funksjonen starter fasen "LOAD" på klokkeslettet "07.02.2026 
16.26.48.422127".

SQL3519W  Start innlasting av konsistenspunkt. Antall inndataposter = "0".

SQL3520W  Innlastingen av konsistenspunkt var vellykket.

SQL3535W  Det er ikke lenger støtte for parameteren "USING" for 
LOAD-kommandoen.  Verdien blir oversett av innlastingsfunksjonen.

SQL3110N  Funksjonen er ferdig med behandlingen. Det ble lest "2081520" rader 
fra inndatafilen.

SQL3519W  Start innlasting av konsistenspunkt. Antall inndataposter = 
"2081520".

SQL3520W  Innlastingen av konsistenspunkt var vellykket.

SQL3515W  Funksjonen avsluttet fasen "LOAD" på klokkeslettet "07.02.2026 
16.27.04.848741".

SQL3500W  Funksjonen starter fasen "BUILD" på klokkeslettet "07.02.2026 
16.27.04.855638".

SQL3213I  Indekseringsmodusen er "REBUILD".

SQL3515W  Funksjonen avsluttet fasen "BUILD" på klokkeslettet "07.02.2026 
16.27.07.105790".


Antall leste rader          = 2081520
Antall utelatte rader       = 0
Antall innlastede rader     = 2081520
Antall avviste rader        = 0
Antall slettede rader       = 0
Antall iverksatte rader     = 2081520

SQL3109N  Hjelperutinen begynner å laste inn data fra filen 
"F:\DRLOAD\DBBKORR.DEL".

SQL3500W  Funksjonen starter fasen "LOAD" på klokkeslettet "14.02.2026 
17.20.15.962071".

SQL3519W  Start innlasting av konsistenspunkt. Antall inndataposter = "0".

SQL3520W  Innlastingen av konsistenspunkt var vellykket.

SQL3535W  Det er ikke lenger støtte for parameteren "USING" for 
LOAD-kommandoen.  Verdien blir oversett av innlastingsfunksjonen.

SQL3110N  Funksjonen er ferdig med behandlingen. Det ble lest "2087171" rader 
fra inndatafilen.

SQL3519W  Start innlasting av konsistenspunkt. Antall inndataposter = 
"2087171".

SQL3520W  Innlastingen av konsistenspunkt var vellykket.

SQL3515W  Funksjonen avsluttet fasen "LOAD" på klokkeslettet "14.02.2026 
17.20.33.725509".

SQL3500W  Funksjonen starter fasen "BUILD" på klokkeslettet "14.02.2026 
17.20.33.731690".

SQL3213I  Indekseringsmodusen er "REBUILD".

SQL3515W  Funksjonen avsluttet fasen "BUILD" på klokkeslettet "14.02.2026 
17.20.35.692421".


Antall leste rader          = 2087171
Antall utelatte rader       = 0
Antall innlastede rader     = 2087171
Antall avviste rader        = 0
Antall slettede rader       = 0
Antall iverksatte rader     = 2087171

SQL3109N  Hjelperutinen begynner å laste inn data fra filen 
"F:\DRLOAD\DBBKORR.DEL".

SQL3500W  Funksjonen starter fasen "LOAD" på klokkeslettet "21.02.2026 
17.22.01.689155".

SQL3519W  Start innlasting av konsistenspunkt. Antall inndataposter = "0".

SQL3520W  Innlastingen av konsistenspunkt var vellykket.

SQL3535W  Det er ikke lenger støtte for parameteren "USING" for 
LOAD-kommandoen.  Verdien blir oversett av innlastingsfunksjonen.

SQL3110N  Funksjonen er ferdig med behandlingen. Det ble lest "2097247" rader 
fra inndatafilen.

SQL3519W  Start innlasting av konsistenspunkt. Antall inndataposter = 
"2097247".

SQL3520W  Innlastingen av konsistenspunkt var vellykket.

SQL3515W  Funksjonen avsluttet fasen "LOAD" på klokkeslettet "21.02.2026 
17.22.19.223522".

SQL3500W  Funksjonen starter fasen "BUILD" på klokkeslettet "21.02.2026 
17.22.19.230688".

SQL3213I  Indekseringsmodusen er "REBUILD".

SQL3515W  Funksjonen avsluttet fasen "BUILD" på klokkeslettet "21.02.2026 
17.22.20.805365".


Antall leste rader          = 2097247
Antall utelatte rader       = 0
Antall innlastede rader     = 2097247
Antall avviste rader        = 0
Antall slettede rader       = 0
Antall iverksatte rader     = 2097247

SQL3109N  Hjelperutinen begynner å laste inn data fra filen 
"F:\DRLOAD\DBBKORR.DEL".

SQL3500W  Funksjonen starter fasen "LOAD" på klokkeslettet "28.02.2026 
16.24.52.905350".

SQL3519W  Start innlasting av konsistenspunkt. Antall inndataposter = "0".

SQL3520W  Innlastingen av konsistenspunkt var vellykket.

SQL3535W  Det er ikke lenger støtte for parameteren "USING" for 
LOAD-kommandoen.  Verdien blir oversett av innlastingsfunksjonen.

SQL3110N  Funksjonen er ferdig med behandlingen. Det ble lest "2106234" rader 
fra inndatafilen.

SQL3519W  Start innlasting av konsistenspunkt. Antall inndataposter = 
"2106234".

SQL3520W  Innlastingen av konsistenspunkt var vellykket.

SQL3515W  Funksjonen avsluttet fasen "LOAD" på klokkeslettet "28.02.2026 
16.25.10.969330".

SQL3500W  Funksjonen starter fasen "BUILD" på klokkeslettet "28.02.2026 
16.25.10.977414".

SQL3213I  Indekseringsmodusen er "REBUILD".

SQL3515W  Funksjonen avsluttet fasen "BUILD" på klokkeslettet "28.02.2026 
16.25.12.432288".


Antall leste rader          = 2106234
Antall utelatte rader       = 0
Antall innlastede rader     = 2106234
Antall avviste rader        = 0
Antall slettede rader       = 0
Antall iverksatte rader     = 2106234

SQL3109N  Hjelperutinen begynner å laste inn data fra filen 
"F:\DRLOAD\DBBKORR.DEL".

SQL3500W  Funksjonen starter fasen "LOAD" på klokkeslettet "07.03.2026 
17.14.12.719509".

SQL3519W  Start innlasting av konsistenspunkt. Antall inndataposter = "0".

SQL3520W  Innlastingen av konsistenspunkt var vellykket.

SQL3535W  Det er ikke lenger støtte for parameteren "USING" for 
LOAD-kommandoen.  Verdien blir oversett av innlastingsfunksjonen.

SQL3110N  Funksjonen er ferdig med behandlingen. Det ble lest "2112933" rader 
fra inndatafilen.

SQL3519W  Start innlasting av konsistenspunkt. Antall inndataposter = 
"2112933".

SQL3520W  Innlastingen av konsistenspunkt var vellykket.

SQL3515W  Funksjonen avsluttet fasen "LOAD" på klokkeslettet "07.03.2026 
17.14.31.538830".

SQL3500W  Funksjonen starter fasen "BUILD" på klokkeslettet "07.03.2026 
17.14.31.546474".

SQL3213I  Indekseringsmodusen er "REBUILD".

SQL3515W  Funksjonen avsluttet fasen "BUILD" på klokkeslettet "07.03.2026 
17.14.33.377298".


Antall leste rader          = 2112933
Antall utelatte rader       = 0
Antall innlastede rader     = 2112933
Antall avviste rader        = 0
Antall slettede rader       = 0
Antall iverksatte rader     = 2112933

SQL3109N  Hjelperutinen begynner å laste inn data fra filen 
"F:\DRLOAD\DBBKORR.DEL".

SQL3500W  Funksjonen starter fasen "LOAD" på klokkeslettet "15.03.2026 
17.23.29.368049".

SQL3519W  Start innlasting av konsistenspunkt. Antall inndataposter = "0".

SQL3520W  Innlastingen av konsistenspunkt var vellykket.

SQL3535W  Det er ikke lenger støtte for parameteren "USING" for 
LOAD-kommandoen.  Verdien blir oversett av innlastingsfunksjonen.

SQL3110N  Funksjonen er ferdig med behandlingen. Det ble lest "2121244" rader 
fra inndatafilen.

SQL3519W  Start innlasting av konsistenspunkt. Antall inndataposter = 
"2121244".

SQL3520W  Innlastingen av konsistenspunkt var vellykket.

SQL3515W  Funksjonen avsluttet fasen "LOAD" på klokkeslettet "15.03.2026 
17.23.47.608908".

SQL3500W  Funksjonen starter fasen "BUILD" på klokkeslettet "15.03.2026 
17.23.47.615642".

SQL3213I  Indekseringsmodusen er "REBUILD".

SQL3515W  Funksjonen avsluttet fasen "BUILD" på klokkeslettet "15.03.2026 
17.23.51.277178".


Antall leste rader          = 2121244
Antall utelatte rader       = 0
Antall innlastede rader     = 2121244
Antall avviste rader        = 0
Antall slettede rader       = 0
Antall iverksatte rader     = 2121244

