connect to basispro user db2nt using ntdb2;

LOAD FROM F:\DRLOAD\DBBKORR.DEL OF DEL MESSAGES LOADBHKORR.MSG REPLACE INTO DBM.BEHOLD_KORR STATISTICS YES AND INDEXES ALL NONRECOVERABLE USING F:\DRLOAD;

