SQL3109N  Hjelperutinen begynner å laste inn data fra filen 
"F:\DRLOAD\DBBKORR.DEL".

SQL3500W  Funksjonen starter fasen "LOAD" på klokkeslettet "09.09.2025 
12.51.32.091665".

SQL3519W  Start innlasting av konsistenspunkt. Antall inndataposter = "0".

SQL3520W  Innlastingen av konsistenspunkt var vellykket.

SQL3535W  Det er ikke lenger støtte for parameteren "USING" for 
LOAD-kommandoen.  Verdien blir oversett av innlastingsfunksjonen.

SQL3110N  Funksjonen er ferdig med behandlingen. Det ble lest "2759163" rader 
fra inndatafilen.

SQL3519W  Start innlasting av konsistenspunkt. Antall inndataposter = 
"2759163".

SQL3520W  Innlastingen av konsistenspunkt var vellykket.

SQL3515W  Funksjonen avsluttet fasen "LOAD" på klokkeslettet "09.09.2025 
12.51.42.971904".

SQL3500W  Funksjonen starter fasen "BUILD" på klokkeslettet "09.09.2025 
12.51.42.978194".

SQL3213I  Indekseringsmodusen er "REBUILD".

SQL3515W  Funksjonen avsluttet fasen "BUILD" på klokkeslettet "09.09.2025 
12.51.45.451385".


Antall leste rader          = 2759163
Antall utelatte rader       = 0
Antall innlastede rader     = 2759163
Antall avviste rader        = 0
Antall slettede rader       = 0
Antall iverksatte rader     = 2759163

