#Requires -Version 7
<#
.SYNOPSIS
  Scans Visual COBOL CBL sources for FKKONTO and rebuilds all.json (FkKonto seed).

.DESCRIPTION
  Finds *.CBL / *.cbl under SourceRoot\cbl containing the literal "FKKONTO",
  excludes files where FKKONTO appears only in comments or known doc-only files,
  and writes all.json next to this script.

.PARAMETER SourceRoot
  Root of Visual COBOL sources (default: C:\opt\data\VisualCobol\Sources).

.PARAMETER OutputFile
  Output JSON path (default: all.generated.json next to this script). Use all.json to overwrite the curated seed.
#>
[CmdletBinding()]
param(
    [string]$SourceRoot = 'C:\opt\data\VisualCobol\Sources',
    [string]$OutputFile = ''
)

$ErrorActionPreference = 'Stop'
$cblDir = Join-Path $SourceRoot 'cbl'
if (-not (Test-Path -LiteralPath $cblDir)) {
    Write-Error "CBL folder not found: $cblDir"
}

# Files where FKKONTO appears only in documentation / comments — exclude from seed
$excludeBasenames = @('ELISABET', 'ILALKTO', 'ILALKTN', 'TPHSCANR')

function Test-FkKontoInActiveCode {
    param([string]$Content)
    $lines = $Content -split "`r?`n"
    foreach ($line in $lines) {
        $trim = $line.TrimStart()
        if ($trim.StartsWith('*')) { continue }
        if ($trim -match '^\s*\*') { continue }
        if ($line -notmatch 'FKKONTO') { continue }
        return $true
    }
    return $false
}

$hits = [System.Collections.Generic.List[string]]::new()
Get-ChildItem -LiteralPath $cblDir -Include '*.CBL', '*.cbl' -File -Recurse | ForEach-Object {
    $base = $_.BaseName.ToUpperInvariant()
    if ($excludeBasenames -contains $base) { return }

    $raw = Get-Content -LiteralPath $_.FullName -Raw -Encoding UTF8
    if ($raw -notmatch 'FKKONTO') { return }

    if (-not (Test-FkKontoInActiveCode -Content $raw)) { return }

    $hits.Add($base)
}

$programs = $hits | Sort-Object -Unique
$outDir = $PSScriptRoot
$entries = [System.Collections.ArrayList]::new()
$i = 1
foreach ($p in $programs) {
    $menuChoice = 'FK{0:D2}' -f $i
    $null = $entries.Add([ordered]@{
        type                 = 'program'
        menuChoice           = $menuChoice
        area                 = 'FkKonto'
        descriptionNorwegian = "Referanse til FKKONTO (generert)"
        description          = "References FKKONTO (auto-generated entry — refine descriptions in all.json)"
        program              = $p
        filetype             = 'cbl'
    })
    $i++
}

$payload = [ordered]@{
    title          = 'FkKonto (Innlan accounting) — COBOL programs referencing the FKKONTO database or FKKONTO ERP data area'
    originalTitle  = 'FkKonto oversikt — programmer som refererer til FKKONTO (generert fra kildekode-søk)'
    generated      = (Get-Date -Format 'yyyy-MM-dd')
    analysisNote   = 'Regenerated by Build-FkKontoAllJson.ps1 — excludes ELISABET, ILALKTO, ILALKTN, TPHSCANR; only lines that are not COBOL comment lines are counted as active references.'
    entries        = @($entries)
}

if (-not $OutputFile) {
    $OutputFile = Join-Path $outDir 'all.generated.json'
} elseif (-not [System.IO.Path]::IsPathRooted($OutputFile)) {
    $OutputFile = Join-Path $outDir $OutputFile
}

$payload | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath $OutputFile -Encoding UTF8
Write-Host "Wrote $($programs.Count) programs to $OutputFile"
