using System.Text.RegularExpressions;

namespace ServerMonitor.Core.Configuration;

/// <summary>
/// Configuration for IIS monitoring
/// </summary>
public class IisMonitoringSettings
{
    /// <summary>
    /// Enable/disable IIS monitoring.
    /// </summary>
    public bool Enabled { get; init; } = true;

    /// <summary>
    /// Regex pattern to match server names where IIS monitoring should be active.
    /// Default: "-app$" (servers ending with "-app").
    /// </summary>
    public string ServerNamePattern { get; init; } = "-app$";

    /// <summary>
    /// Check if the given computer name matches the ServerNamePattern.
    /// </summary>
    public bool IsServerNameMatch(string computerName)
    {
        if (string.IsNullOrEmpty(ServerNamePattern)) return true;
        try
        {
            return Regex.IsMatch(computerName, ServerNamePattern, RegexOptions.IgnoreCase);
        }
        catch
        {
            return computerName.EndsWith("-app", StringComparison.OrdinalIgnoreCase);
        }
    }

    /// <summary>
    /// Collection/refresh interval in seconds. Default: 300 (5 minutes).
    /// </summary>
    public int PollingIntervalSeconds { get; init; } = 300;

    /// <summary>
    /// Generate alerts when application pools configured for auto-start are stopped.
    /// </summary>
    public bool AlertOnStoppedAppPools { get; init; } = true;

    /// <summary>
    /// Generate alerts when sites are stopped.
    /// </summary>
    public bool AlertOnStoppedSites { get; init; } = true;

    /// <summary>
    /// Worker process private memory threshold in MB. Alert if a worker process exceeds this.
    /// Default: 2048 MB (2 GB). Set to 0 to disable.
    /// </summary>
    public int WorkerProcessMemoryThresholdMB { get; init; } = 2048;

    /// <summary>
    /// Whether the Dashboard can show a pop-out window for IIS details.
    /// </summary>
    public bool EnableDashboardPopout { get; init; } = true;

    /// <summary>
    /// Alert configuration
    /// </summary>
    public IisAlerts Alerts { get; init; } = new();

    /// <summary>
    /// List of channel types to suppress for alerts generated by this monitor.
    /// </summary>
    public List<string> SuppressedChannels { get; init; } = new();
}

/// <summary>
/// Alert settings for IIS monitoring
/// </summary>
public class IisAlerts
{
    public string StoppedAppPoolSeverity { get; init; } = "Critical";
    public string StoppedSiteSeverity { get; init; } = "Critical";
    public string WorkerProcessMemorySeverity { get; init; } = "Warning";

    /// <summary>
    /// Maximum occurrences before triggering an alert. Default: 0 (immediate alert).
    /// </summary>
    public int MaxOccurrences { get; init; } = 0;

    /// <summary>
    /// Time window in minutes for counting occurrences AND cooldown after alerting.
    /// Default: 15 minutes.
    /// </summary>
    public int TimeWindowMinutes { get; init; } = 15;
}
