setx DB2DATABASE_PORT 25000 /m

set COMPUTERNAME=%COMPUTERNAME%

if "%COMPUTERNAME%"=="t-no1fkmdev-db" (
    setx DB2DATABASE_DATABASE_NAME FKMDEV /m
    setx DB2DATABASE_ALIAS1_NAME FKAVDNT /m
    setx DB2DATABASE_ALIAS1_PORT 3710 /m
)
if "%COMPUTERNAME%"=="t-no1fkmtst-db" (
    setx DB2DATABASE_DATABASE_NAME FKMTST /m
    setx DB2DATABASE_ALIAS1_NAME BASISTST /m
    setx DB2DATABASE_ALIAS1_PORT 3701 /m
)
if "%COMPUTERNAME%"=="p-no1fkmprd-db" (
    setx DB2DATABASE_DATABASE_NAME FKMPRD /m
    setx DB2DATABASE_ALIAS1_NAME BASISREG /m
    setx DB2DATABASE_ALIAS1_PORT 3700 /m
)
if "%COMPUTERNAME%"=="p-no1fkmrap-db" (
    setx DB2DATABASE_DATABASE_NAME FKMRAP /m
    setx DB2DATABASE_ALIAS1_NAME BASISRAP /m
    setx DB2DATABASE_ALIAS1_PORT 3700 /m
)
if "%COMPUTERNAME%"=="p-no1fkmhst-db" (
    setx DB2DATABASE_DATABASE_NAME FKMDEV /m
    setx DB2DATABASE_ALIAS1_NAME BASISHST /m
    setx DB2DATABASE_ALIAS1_PORT 3700 /m
)
if "%COMPUTERNAME%"=="t-no1fkmmig-db" (
    setx DB2DATABASE_DATABASE_NAME FKMMIG /m
    setx DB2DATABASE_ALIAS1_NAME BASISMIG /m
    setx DB2DATABASE_ALIAS1_PORT 3711 /m
)
if "%COMPUTERNAME%"=="t-no1fkmsit-db" (
    setx DB2DATABASE_DATABASE_NAME FKMSIT /m
    setx DB2DATABASE_ALIAS1_NAME BASISSIT /m
    setx DB2DATABASE_ALIAS1_PORT 3711 /m
)
if "%COMPUTERNAME%"=="t-no1fkmvft-db" (
    setx DB2DATABASE_DATABASE_NAME FKMVFT /m
    setx DB2DATABASE_ALIAS1_NAME BASISVFT /m
    setx DB2DATABASE_ALIAS1_PORT 3711 /m
)
if "%COMPUTERNAME%"=="t-no1fkmvfk-db" (
    setx DB2DATABASE_DATABASE_NAME FKMVFK /m
    setx DB2DATABASE_ALIAS1_NAME BASISVFK /m
    setx DB2DATABASE_ALIAS1_PORT 3711 /m
)
if "%COMPUTERNAME%"=="p-no1inlprd-db" (
    setx DB2DATABASE_DATABASE_NAME INLPRD /m
    setx DB2DATABASE_ALIAS1_NAME FKKONTO /m
    setx DB2DATABASE_ALIAS1_PORT 3705 /m
)
if "%COMPUTERNAME%"=="t-no1inltst-db" (
    setx DB2DATABASE_DATABASE_NAME INLTST /m
    setx DB2DATABASE_ALIAS1_NAME FKKONTO /m
    setx DB2DATABASE_ALIAS1_PORT 3706 /m
)

