# Import-Module GlobalFunctions -Force

<#
.SYNOPSIS
Imports server tasks into Azure DevOps as work items.

.DESCRIPTION
This script reads the Azure DevOps compatible task files generated by ServerTaskGenerator.ps1
and imports them into Azure DevOps as work items using the REST API.

.PARAMETER Pat
Personal Access Token with permissions to create work items in Azure DevOps.

.PARAMETER Organization
The name of your Azure DevOps organization.

.PARAMETER Project
The name of your Azure DevOps project.

.PARAMETER AreaPath
The area path to assign to created work items.

.PARAMETER IterationPath
The iteration path to assign to created work items.

.PARAMETER TaskFilesPath
Path to the Azure DevOps task files generated by ServerTaskGenerator.ps1.

.EXAMPLE
.\ImportTasksToAzureDevOps.ps1 -Pat "yourpat" -Organization "yourorg" -Project "yourproject" -AreaPath "YourProject\ServerTasks" -IterationPath "YourProject\Sprint 1"

.NOTES
Requires PowerShell 5.1 or later.
Make sure your PAT has the necessary permissions (Work Items: Read, Write & Manage).
#>

# Default configuration
$config = @{
    Organization = "Dedge"
    Project      = "Dedge"
    Repository   = "Dedge"
    #Pat = "f53cdny64fbuehfy3rofdbz5mxgjnvhlxwmgbjrazg745uey4euq"  # Personal access token (old GHS)
    Pat          = "1tUXXsW0bstSLZynGlyR5E7C77GKhIi3gyup9IAqOFvQqe0EXKFDJQQJ99AKACAAAAAMSOigAAASAZDOCmX6"  # Personal access token (new Dedge srv_Dedge_repo@Dedge.onmicrosoft.com)
}

param (
    [Parameter(Mandatory = $false)]
    [string]$Pat = $config.Pat,

    [Parameter(Mandatory = $false)]
    [string]$Organization = $config.Organization,

    [Parameter(Mandatory = $false)]
    [string]$Project = $config.Project,

    [Parameter(Mandatory = $true)]
    [string]$AreaPath,

    [Parameter(Mandatory = $true)]
    [string]$IterationPath,

    [Parameter(Mandatory = $false)]
    [string]$TaskFilesPath
)

# If TaskFilesPath is not provided, use the default path
if (-not $TaskFilesPath) {
    $scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
    $migrationPlanPath = Join-Path $scriptDir "_MigrationPlan"
    $TaskFilesPath = Join-Path $migrationPlanPath "AzureDevOpsTasks"
}

# Check if the task files path exists
if (-not (Test-Path $TaskFilesPath)) {
    Write-Error "The specified TaskFilesPath does not exist: $TaskFilesPath"
    exit 1
}

# Base64 encode the Personal Access Token (PAT) for authorization
$base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(":$($Pat)"))
$headers = @{
    "Authorization" = "Basic $base64AuthInfo"
    "Content-Type" = "application/json-patch+json"
}

# Get all ADO task files
$adoTaskFiles = Get-ChildItem -Path $TaskFilesPath -Filter "*.ado.json" -Recurse

# Track created tasks for dependency linking
$createdTasks = @{}

# Function to create a work item in Azure DevOps
function Create-WorkItem {
    param (
        [string]$Title,
        [array]$Fields
    )

    # Add common fields
    $Fields += @(
        @{
            op = "add"
            path = "/fields/System.AreaPath"
            value = $AreaPath
        },
        @{
            op = "add"
            path = "/fields/System.IterationPath"
            value = $IterationPath
        },
        @{
            op = "add"
            path = "/fields/System.WorkItemType"
            value = "Task"
        }
    )

    # Create the request body
    $body = ConvertTo-Json -InputObject $Fields -Depth 10

    # Define the API endpoint for creating a work item
    $uri = "https://dev.azure.com/$Organization/$Project/_apis/wit/workitems/`$Task?api-version=6.0"

    try {
        Write-Host "Creating task: $Title"
        $response = Invoke-RestMethod -Uri $uri -Method Post -Headers $headers -Body $body -ErrorAction Stop

        # Return the created work item info
        return @{
            Id = $response.id
            Title = $response.fields.'System.Title'
            Url = $response.url
        }
    }
    catch {
        Write-Error "Failed to create task: $Title"
        Write-Error "API Error: $_"
        return $null
    }
}

# Function to create a relation between work items (for prerequisites)
function Add-WorkItemRelation {
    param (
        [int]$SourceId,
        [int]$TargetId,
        [string]$RelationType = "System.LinkTypes.Dependency-forward"
    )

    $relation = @{
        op = "add"
        path = "/relations/-"
        value = @{
            rel = $RelationType
            url = "https://dev.azure.com/$Organization/$Project/_apis/wit/workItems/$TargetId"
        }
    }

    $body = ConvertTo-Json -InputObject @($relation) -Depth 10
    $uri = "https://dev.azure.com/$Organization/$Project/_apis/wit/workitems/$SourceId/?api-version=6.0"

    try {
        Write-Host "Adding relation: Task $SourceId depends on Task $TargetId"
        Invoke-RestMethod -Uri $uri -Method Patch -Headers $headers -Body $body -ErrorAction Stop | Out-Null
        return $true
    }
    catch {
        Write-Error "Failed to create relation between $SourceId and $TargetId"
        Write-Error "API Error: $_"
        return $false
    }
}

# Main import process
Write-Host "Starting task import to Azure DevOps..."
Write-Host "Organization: $Organization"
Write-Host "Project: $Project"
Write-Host "Area Path: $AreaPath"
Write-Host "Iteration Path: $IterationPath"
Write-Host "Processing $($adoTaskFiles.Count) server task files..."

foreach ($adoTaskFile in $adoTaskFiles) {
    # Read the ADO task file
    $adoTaskData = Get-Content -Path $adoTaskFile.FullName -Raw | ConvertFrom-Json

    Write-Host "`nProcessing server: $($adoTaskData.server) from template: $($adoTaskData.templateName)"

    # Track the tasks for this server
    $serverTasks = @{}
    $serverTaskDependencies = @{}

    # First pass: Create all tasks
    foreach ($task in $adoTaskData.tasks) {
        $taskName = $task.taskname

        # Extract fields, add a custom field to store prerequisite task names
        $taskFields = $task.fields

        # Create the work item
        $createdTask = Create-WorkItem -Title $taskName -Fields $taskFields

        if ($createdTask) {
            # Store the created task ID
            $serverTasks[$taskName] = $createdTask.Id
            $createdTasks[$taskName] = $createdTask.Id

            # Extract prerequisite tasks from the acceptance criteria if present
            $acceptanceCriteriaField = $taskFields | Where-Object { $_.path -eq "/fields/Microsoft.VSTS.Common.AcceptanceCriteria" } | Select-Object -First 1

            if ($acceptanceCriteriaField) {
                $prerequisites = $acceptanceCriteriaField.value -replace "Prerequisites: ", "" -split "; "
                if ($prerequisites.Count -gt 0) {
                    $serverTaskDependencies[$taskName] = $prerequisites
                }
            }
        }
    }

    # Second pass: Create task dependencies
    foreach ($taskName in $serverTaskDependencies.Keys) {
        $sourceId = $serverTasks[$taskName]

        foreach ($prereqTask in $serverTaskDependencies[$taskName]) {
            if ($serverTasks.ContainsKey($prereqTask)) {
                $targetId = $serverTasks[$prereqTask]
                Add-WorkItemRelation -SourceId $sourceId -TargetId $targetId
            }
            else {
                Write-Warning "Prerequisite task not found: $prereqTask"
            }
        }
    }

    Write-Host "Created $($serverTasks.Count) tasks for server $($adoTaskData.server)."
}

Write-Host "`nTask import completed. Created $($createdTasks.Count) tasks in total."

