#Requires -Version 7
<#
.SYNOPSIS
  Finds CBL programs whose SQL references DBM.MODUL (COBDOK module table, not MODUL_LINJER).

.PARAMETER SourceRoot
  Visual COBOL sources root (default: C:\opt\data\VisualCobol\Sources).

.PARAMETER OutputFile
  Default: all.generated.json beside this script.
#>
[CmdletBinding()]
param(
    [string]$SourceRoot = 'C:\opt\data\VisualCobol\Sources',
    [string]$OutputFile = ''
)

$ErrorActionPreference = 'Stop'
$cblDir = Join-Path $SourceRoot 'cbl'
if (-not (Test-Path -LiteralPath $cblDir)) {
    Write-Error "CBL folder not found: $cblDir"
}

# Match DBM.MODUL as table name but not DBM.MODUL_LINJER
$rx = [regex]::new('DBM\.MODUL(?:\s|,|\)|;|$|/|\.)', [System.Text.RegularExpressions.RegexOptions]::IgnoreCase)

$hits = [System.Collections.Generic.HashSet[string]]::new([StringComparer]::OrdinalIgnoreCase)

# -Include with -Recurse requires trailing * on path; filter by extension instead
Get-ChildItem -LiteralPath $cblDir -Recurse -File -ErrorAction SilentlyContinue |
    Where-Object { $_.Extension -match '^\.cbl$' } |
    ForEach-Object {
    $raw = Get-Content -LiteralPath $_.FullName -Raw -Encoding UTF8
    if ($rx.IsMatch($raw)) {
        $null = $hits.Add($_.BaseName.ToUpperInvariant())
    }
}

$programs = $hits | Sort-Object
$entries = [System.Collections.ArrayList]::new()
$i = 1
foreach ($p in $programs) {
    $null = $entries.Add([ordered]@{
        type                 = 'program'
        menuChoice           = 'CD{0:D2}' -f $i
        area                 = 'CobDok'
        descriptionNorwegian = 'Referanse til DBM.MODUL (generert)'
        description          = 'References DBM.MODUL table (auto-generated)'
        program              = $p
        filetype             = 'cbl'
    })
    $i++
}

$outDir = $PSScriptRoot
if (-not $OutputFile) {
    $OutputFile = Join-Path $outDir 'all.generated.json'
} elseif (-not [System.IO.Path]::IsPathRooted($OutputFile)) {
    $OutputFile = Join-Path $outDir $OutputFile
}

$payload = [ordered]@{
    title         = 'CobDok — COBOL programs using DBM.MODUL in the COBDOK documentation database'
    originalTitle = 'CobDok — DBM.MODUL (generert)'
    generated     = (Get-Date -Format 'yyyy-MM-dd')
    analysisNote  = 'Regenerated by Build-CobDokAllJson.ps1 — table is DBM.MODUL (singular), not MODULES.'
    entries       = @($entries)
}

$payload | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath $OutputFile -Encoding UTF8
Write-Host "Wrote $($programs.Count) programs to $OutputFile"
