
Import-Module ScheduledTask-Handler -Force
Import-Module GlobalFunctions -Force
$outFile = "$PsScriptRoot\Generated-ScheduledTasks-AddServerTasks.txt"
"REM ################# Auto-Import of Scheduled Tasks from Xml files ##############" | Out-File $outFile -Append -Encoding utf8
"REM    This batch file was generated by ScheduledTasks-AddServerTasks.ps1" | Out-File $outFile -Append -Encoding utf8
"REM    Paste the content into an admin cmd.exe to import the scheduled tasks" | Out-File $outFile -Append -Encoding utf8
"REM    but do not call it directly, it will not work" | Out-File $outFile -Append -Encoding utf8
"REM    !!! PS. Delete the file after use to avoid password exposure !!!" | Out-File $outFile -Append -Encoding utf8
"REM ##############################################################################" | Out-File $outFile -Append -Encoding utf8

$customTasksPath = "$PsScriptRoot\customtasks\$computerName"
$matchingFoldersWithComputerName = $($(Get-ChildItem -Path "$PsScriptRoot\customtasks" -Recurse ).FullName) | Where-Object { $_.ToLower().Contains($env:COMPUTERNAME.ToLower()) }
$credentialsArgs = Get-ScheduledTaskCredentials -RunAsUser $true
$setCommand = "set password=$($credentialsArgs[-1])"
Write-Host $setCommand -Level INFO
$setCommand | Out-File $outFile -Append -Encoding utf8
$credentialsArgs[-1] = "`"%password%`""

Write-LogMessage "Running automated scheduled task creation on $computerName" -Level INFO
foreach ($customTasksPath in $matchingFoldersWithComputerName) {
    if (Test-Path $customTasksPath -PathType Container) {
        $xmlFiles = Get-ChildItem -Path "$customTasksPath\*" -Recurse -Include *.xml
        foreach ($xmlFile in $xmlFiles) {
            $taskName = $($xmlFile.FullName.Split("$env:COMPUTERNAME")[-1]).TrimStart("\").TrimEnd(".xml")

            $schtaskExePath = Get-CommandPathWithFallback -Name "schtasks"
            $deleteCommand = "$schtaskExePath /Delete /TN `"$taskName`" /F"
            try {
                $deleteCommand | Out-File $outFile -Append -Encoding utf8
            }
            catch {
                Write-LogMessage "Error: $($_.Exception.Message)" -Level ERROR -Exception $_
            }

            $createCommand = "$schtaskExePath /Create /XML `"$($xmlFile.FullName)`" /tn `"$taskName`""
            $createCommand += " $credentialsArgs"
            Write-LogMessage $createCommand -Level INFO

            try {
                $createCommand | Out-File $outFile -Append -Encoding utf8
            }
            catch {
                Write-LogMessage "Error: $($_.Exception.Message)" -Level ERROR -Exception $_
                & "$env:USERPROFILE\AppData\Local\Programs\Microsoft VS Code\Code.exe" $($xmlFile.FullName)
                Write-Host "Press Enter to continue..."
                Read-Host
            }
        }
    }
}

$setCommand = "set `"password=`""
$setCommand | Out-File $outFile -Append -Encoding utf8

Write-Host "Batch file generated: $outFile" -Level INFO
Write-Host "Paste the content into an admin cmd.exe to import the scheduled tasks" -Level INFO
notepad $outFile
Read-Host "After you have imported the scheduled tasks, press Enter to delete the auto-generated file to avoid password exposure..."
Remove-Item $outFile -Force

