Import-Module GlobalFunctions -Force
Import-Module Db2-Handler -Force

$fedDb = "XFKMTST"
$fedInstance = "DB2FED"

Write-LogMessage "=== Verifying grants on $($fedDb) (instance $($fedInstance)) ===" -Level INFO

$db2Commands = @()
$db2Commands += "set DB2INSTANCE=$($fedInstance)"
$db2Commands += "db2 connect to $($fedDb)"

$db2Commands += "REM === Phase 1: Check GRANT SELECT on nicknames (sample top 20) ==="
$db2Commands += "db2 `"SELECT CHAR(TABSCHEMA, 20) AS SCHEMA, CHAR(TABNAME, 40) AS NICKNAME, CHAR(GRANTEETYPE, 1) AS GTYPE, CHAR(GRANTEE, 20) AS GRANTEE, SELECTAUTH, INSERTAUTH, UPDATEAUTH, DELETEAUTH FROM SYSCAT.TABAUTH WHERE GRANTEE = 'PUBLIC' AND GRANTEETYPE = '' FETCH FIRST 20 ROWS ONLY`""

$db2Commands += "REM === Phase 2: Count nicknames with SELECT granted to PUBLIC ==="
$db2Commands += "db2 `"SELECT COUNT(*) AS NICKNAMES_WITH_SELECT_TO_PUBLIC FROM SYSCAT.TABAUTH A INNER JOIN SYSCAT.NICKNAMES N ON A.TABSCHEMA = N.TABSCHEMA AND A.TABNAME = N.TABNAME WHERE A.GRANTEE = 'PUBLIC' AND A.SELECTAUTH = 'Y'`""

$db2Commands += "REM === Phase 3: Count total nicknames ==="
$db2Commands += "db2 `"SELECT COUNT(*) AS TOTAL_NICKNAMES FROM SYSCAT.NICKNAMES`""

$db2Commands += "REM === Phase 4: Nicknames WITHOUT SELECT grant to PUBLIC ==="
$db2Commands += "db2 `"SELECT CHAR(N.TABSCHEMA, 20) AS SCHEMA, CHAR(N.TABNAME, 40) AS NICKNAME FROM SYSCAT.NICKNAMES N WHERE NOT EXISTS (SELECT 1 FROM SYSCAT.TABAUTH A WHERE A.TABSCHEMA = N.TABSCHEMA AND A.TABNAME = N.TABNAME AND A.GRANTEE = 'PUBLIC' AND A.SELECTAUTH = 'Y') FETCH FIRST 30 ROWS ONLY`""

$db2Commands += "REM === Phase 5: Count nicknames WITHOUT SELECT to PUBLIC ==="
$db2Commands += "db2 `"SELECT COUNT(*) AS NICKNAMES_WITHOUT_SELECT FROM SYSCAT.NICKNAMES N WHERE NOT EXISTS (SELECT 1 FROM SYSCAT.TABAUTH A WHERE A.TABSCHEMA = N.TABSCHEMA AND A.TABNAME = N.TABNAME AND A.GRANTEE = 'PUBLIC' AND A.SELECTAUTH = 'Y')`""

$db2Commands += "REM === Phase 6: Check GRANT EXECUTE on routines (functions/procedures) ==="
$db2Commands += "db2 `"SELECT CHAR(R.ROUTINESCHEMA, 20) AS SCHEMA, CHAR(R.ROUTINENAME, 40) AS ROUTINE, CHAR(R.ROUTINETYPE, 1) AS RTYPE, CHAR(A.GRANTEE, 20) AS GRANTEE, A.EXECUTEAUTH FROM SYSCAT.ROUTINEAUTH A INNER JOIN SYSCAT.ROUTINES R ON A.SPECIFICNAME = R.SPECIFICNAME AND A.SCHEMA = R.ROUTINESCHEMA WHERE A.GRANTEE = 'PUBLIC' AND R.ROUTINESCHEMA NOT LIKE 'SYS%' FETCH FIRST 30 ROWS ONLY`""

$db2Commands += "REM === Phase 7: Count routines with EXECUTE to PUBLIC ==="
$db2Commands += "db2 `"SELECT COUNT(*) AS ROUTINES_WITH_EXEC_TO_PUBLIC FROM SYSCAT.ROUTINEAUTH A INNER JOIN SYSCAT.ROUTINES R ON A.SPECIFICNAME = R.SPECIFICNAME AND A.SCHEMA = R.ROUTINESCHEMA WHERE A.GRANTEE = 'PUBLIC' AND A.EXECUTEAUTH = 'Y' AND R.ROUTINESCHEMA NOT LIKE 'SYS%'`""

$db2Commands += "REM === Phase 8: Total non-system routines ==="
$db2Commands += "db2 `"SELECT COUNT(*) AS TOTAL_ROUTINES FROM SYSCAT.ROUTINES WHERE ROUTINESCHEMA NOT LIKE 'SYS%' AND ROUTINETYPE IN ('F', 'P')`""

$db2Commands += "REM === Phase 9: Routines WITHOUT EXECUTE to PUBLIC ==="
$db2Commands += "db2 `"SELECT CHAR(R.ROUTINESCHEMA, 20) AS SCHEMA, CHAR(R.ROUTINENAME, 40) AS ROUTINE, CHAR(R.ROUTINETYPE, 1) AS RTYPE FROM SYSCAT.ROUTINES R WHERE R.ROUTINESCHEMA NOT LIKE 'SYS%' AND R.ROUTINETYPE IN ('F', 'P') AND NOT EXISTS (SELECT 1 FROM SYSCAT.ROUTINEAUTH A WHERE A.SPECIFICNAME = R.SPECIFICNAME AND A.SCHEMA = R.ROUTINESCHEMA AND A.GRANTEE = 'PUBLIC' AND A.EXECUTEAUTH = 'Y') FETCH FIRST 30 ROWS ONLY`""

$db2Commands += "REM === Phase 10: Count routines WITHOUT EXECUTE to PUBLIC ==="
$db2Commands += "db2 `"SELECT COUNT(*) AS ROUTINES_WITHOUT_EXEC FROM SYSCAT.ROUTINES R WHERE R.ROUTINESCHEMA NOT LIKE 'SYS%' AND R.ROUTINETYPE IN ('F', 'P') AND NOT EXISTS (SELECT 1 FROM SYSCAT.ROUTINEAUTH A WHERE A.SPECIFICNAME = R.SPECIFICNAME AND A.SCHEMA = R.ROUTINESCHEMA AND A.GRANTEE = 'PUBLIC' AND A.EXECUTEAUTH = 'Y')`""

$db2Commands += "db2 terminate"

$workFolder = Join-Path $env:OptPath "data\Db2-FederationHandler\VerifyGrants"
New-Item -Path $workFolder -ItemType Directory -Force -ErrorAction SilentlyContinue | Out-Null

$fileName = Join-Path $workFolder "VerifyGrants_$(Get-Date -Format 'yyyyMMddHHmmssfff').bat"
$output = Invoke-Db2ContentAsScript -Content $db2Commands -ExecutionType BAT -IgnoreErrors -FileName $fileName

Write-LogMessage "=== Full DB2 output ===" -Level INFO
Write-Host $output
Write-LogMessage "=== Grant verification complete ===" -Level INFO
