-- =============================================
-- DBQA Database Objects Management Script
-- Purpose: Creates and manages database objects for quality assurance
-- =============================================
-- Dependencies:
-- System Tables/Views Used:
--   SYSCAT.TABLES
--     └─ Used for table existence checks
--   SYSCAT.COLUMNS
--     └─ Used for column validation
--   SYSCAT.ROUTINES
--     └─ Used for stored procedure/function info
--
-- Table Dependencies:
--   DBM.DBQA_APPLICATION_SYSTEM
--     └─ Referenced by: DBQA_PACKAGE_METAINFO
--     └─ No external dependencies
--   DBM.DBQA_PACKAGE_METAINFO
--     └─ References: DBQA_APPLICATION_SYSTEM
--     └─ Used by: Analysis views
--   DBM.DBQA_SQL_ANALYSIS
--     └─ Referenced by: DBQA_STATEMENT_PARTS
--     └─ Used by: Analysis views
--   DBM.DBQA_STATEMENT_PARTS
--     └─ References: DBQA_SQL_ANALYSIS
--     └─ Referenced by: DBQA_CONSUMED_OBJECTS
--   DBM.DBQA_CONSUMED_OBJECTS
--     └─ References: DBQA_STATEMENT_PARTS
--     └─ Used by: Dependency analysis views
--   DBM.DBQA_PACKAGE_SOURCE_EXISTENCE
--     └─ Independent table for source tracking
--     └─ Used by: Package analysis views
-- =============================================

-- =============================================
-- Cleanup Section: Drop existing objects
-- =============================================
-- Drop all DBQA-related views first (ignore errors if objects don't exist)
CONNECT TO DBQTST;
-- CREATE SCHEMA DBM;
-- CREATE SCHEMA TV;

-- BEGIN
--   DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
  
--   -- Drop views that are created in this file
--   EXECUTE IMMEDIATE 'DROP VIEW TV.V_DBQA_VIEWS_NOT_ACCESSED_INTERNALLY';
--   EXECUTE IMMEDIATE 'DROP VIEW TV.V_UNUSED_PACKAGES_ANALYSIS';
--   EXECUTE IMMEDIATE 'DROP VIEW TV.V_DBQA_MIGRATION_TABLES_DB2_115';
--   EXECUTE IMMEDIATE 'DROP VIEW TV.V_DBQA_PACKAGE_MISSING_CBL_SOURCE';
--   EXECUTE IMMEDIATE 'DROP VIEW TV.V_DBQA_STATEMENT_PARTS_HASH_CHK';  
--   EXECUTE IMMEDIATE 'DROP VIEW TV.V_DBQA_SOURCE_DIFFERENCES';  
-- END;

-- -- Drop all DBQA-related tables (in correct dependency order)
-- BEGIN
--   DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
  
--   -- Drop tables in dependency order to handle foreign key constraints
--   EXECUTE IMMEDIATE 'DROP TABLE DBM.DBQA_CONSUMED_OBJECTS';
--   EXECUTE IMMEDIATE 'DROP TABLE DBM.DBQA_STATEMENT_PARTS';
--   EXECUTE IMMEDIATE 'DROP TABLE DBM.DBQA_SQL_ANALYSIS';
--   EXECUTE IMMEDIATE 'DROP TABLE DBM.DBQA_PACKAGE_SOURCE_EXISTENCE';
--   EXECUTE IMMEDIATE 'DROP TABLE DBM.DBQA_PACKAGE_METAINFO';
--   EXECUTE IMMEDIATE 'DROP TABLE DBM.DBQA_APPLICATION_SYSTEM';
-- END;

-- =============================================
-- Application System Management Tables
-- =============================================
-- Tables for managing application system configurations and mappings
CREATE TABLE DBM.DBQA_APPLICATION_SYSTEM (
    
    APPLICATION_NAME VARCHAR(128) NOT null,        
    SYSTEM_CODE VARCHAR(128) NOT null,        
    DESCRIPTION VARCHAR(128),             
    PRIMARY KEY (APPLICATION_NAME ,SYSTEM_CODE)
);

COMMENT ON TABLE DBM.DBQA_APPLICATION_SYSTEM IS 'Master table for application system mappings and configurations. Maintains relationships between applications and their system codes for configuration management.';
COMMENT ON COLUMN DBM.DBQA_APPLICATION_SYSTEM.APPLICATION_NAME IS 'Unique identifier for the application';
COMMENT ON COLUMN DBM.DBQA_APPLICATION_SYSTEM.SYSTEM_CODE IS 'System-specific identifier code';
COMMENT ON COLUMN DBM.DBQA_APPLICATION_SYSTEM.DESCRIPTION IS 'Descriptive text about the application system';

GRANT CONTROL ON TABLE DBM.DBQA_APPLICATION_SYSTEM TO FKGEISTA;
GRANT CONTROL ON TABLE DBM.DBQA_APPLICATION_SYSTEM TO FKSVEERI;
GRANT SELECT ON TABLE DBM.DBQA_APPLICATION_SYSTEM TO PUBLIC;
CREATE INDEX IDX_DBQA_APP_SYS ON DBM.DBQA_APPLICATION_SYSTEM(APPLICATION_NAME, SYSTEM_CODE);
COMMIT; 

-- =============================================
-- Package Metadata Management Tables
-- =============================================
-- Tables for tracking package configurations and status
CREATE TABLE DBM.DBQA_PACKAGE_METAINFO (
    APPLICATION_NAME VARCHAR(128) NOT NULL,  
    SOURCE_SCHEMA_NAME VARCHAR(128)  NOT NULL,
    SOURCE_NAME VARCHAR(128) NOT NULL, 
    OBJECT_TYPE VARCHAR(128) NOT NULL, 
    OBJECT_NAME VARCHAR(128),
    DESCRIPTION VARCHAR(768), 
    SYSTEM_CODE VARCHAR(128), 
    IS_DISCARDED SMALLINT DEFAULT 0, 
    SIMULATE_IS_DISCARDED SMALLINT DEFAULT 0, 
    PRIMARY KEY ( APPLICATION_NAME , SOURCE_SCHEMA_NAME, SOURCE_NAME, OBJECT_TYPE  )
);

COMMENT ON TABLE DBM.DBQA_PACKAGE_METAINFO IS 'Central repository for package metadata and status tracking. Stores detailed information about package configurations, status, and relationships.';
COMMENT ON COLUMN DBM.DBQA_PACKAGE_METAINFO.APPLICATION_NAME IS 'Name of the application owning the package';
COMMENT ON COLUMN DBM.DBQA_PACKAGE_METAINFO.SOURCE_SCHEMA_NAME IS 'Schema name containing the source object';
COMMENT ON COLUMN DBM.DBQA_PACKAGE_METAINFO.SOURCE_NAME IS 'Name of the source package';
COMMENT ON COLUMN DBM.DBQA_PACKAGE_METAINFO.OBJECT_TYPE IS 'Type of the source (e.g., SQL, COBOL)';
COMMENT ON COLUMN DBM.DBQA_PACKAGE_METAINFO.OBJECT_NAME IS 'Name of the database object';
COMMENT ON COLUMN DBM.DBQA_PACKAGE_METAINFO.DESCRIPTION IS 'Detailed description of the package';
COMMENT ON COLUMN DBM.DBQA_PACKAGE_METAINFO.SYSTEM_CODE IS 'Associated system code';
COMMENT ON COLUMN DBM.DBQA_PACKAGE_METAINFO.IS_DISCARDED IS 'Flag indicating if package is discarded (1=yes, 0=no)';
COMMENT ON COLUMN DBM.DBQA_PACKAGE_METAINFO.SIMULATE_IS_DISCARDED IS 'Simulation flag for testing package removal (1=yes, 0=no)';
   
GRANT CONTROL ON TABLE DBM.DBQA_PACKAGE_METAINFO TO FKGEISTA;
GRANT CONTROL ON TABLE DBM.DBQA_PACKAGE_METAINFO TO FKSVEERI;
GRANT SELECT ON TABLE DBM.DBQA_PACKAGE_METAINFO TO PUBLIC;
CREATE INDEX IDX_DBQA_PKG_META ON DBM.DBQA_PACKAGE_METAINFO(SOURCE_SCHEMA_NAME, SOURCE_NAME);
COMMIT; 

-- =============================================
-- SQL Analysis Tables
-- =============================================
-- Tables for analyzing and tracking SQL statements
CREATE TABLE DBM.DBQA_SQL_ANALYSIS (
    DBQA_SQL_ANALYSIS_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    APPLICATION_NAME VARCHAR(128) NOT null,        
    ENVIRONMENT_NAME VARCHAR(128) NOT null,        
    SOURCE_SCHEMA_NAME VARCHAR(128)  NOT NULL,
    SOURCE_NAME VARCHAR(128) NOT NULL, 
    OBJECT_TYPE VARCHAR(128) NOT NULL, 
    OBJECT_NAME VARCHAR(128),
    COMPLETE_STATEMENT_TEXT VARCHAR(30000),         
    COMPLETE_STATEMENT_HASH CHAR(64),
    CREATED_BY VARCHAR(128) DEFAULT USER,             
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    FILE_NAME VARCHAR(768) DEFAULT NULL,             
    LAST_DDL_TIMESTAMP TIMESTAMP DEFAULT NULL,
    LAST_DDL_USER_ID VARCHAR(128),
    PRIMARY KEY (DBQA_SQL_ANALYSIS_ID)
);
COMMIT;
COMMENT ON TABLE DBM.DBQA_SQL_ANALYSIS IS 'Primary table for SQL statement analysis and tracking. Stores complete SQL statements with their metadata for analysis and monitoring.';
COMMENT ON COLUMN DBM.DBQA_SQL_ANALYSIS.DBQA_SQL_ANALYSIS_ID IS 'Unique identifier for the analysis record';
COMMENT ON COLUMN DBM.DBQA_SQL_ANALYSIS.APPLICATION_NAME IS 'Name of the application containing the SQL';
COMMENT ON COLUMN DBM.DBQA_SQL_ANALYSIS.ENVIRONMENT_NAME IS 'Environment where the SQL was analyzed';
COMMENT ON COLUMN DBM.DBQA_SQL_ANALYSIS.SOURCE_SCHEMA_NAME IS 'Schema name containing the source object';
COMMENT ON COLUMN DBM.DBQA_SQL_ANALYSIS.SOURCE_NAME IS 'Name of the source object';
COMMENT ON COLUMN DBM.DBQA_SQL_ANALYSIS.OBJECT_TYPE IS 'Type of source containing the SQL';
COMMENT ON COLUMN DBM.DBQA_SQL_ANALYSIS.OBJECT_NAME IS 'Name of the analyzed object';
COMMENT ON COLUMN DBM.DBQA_SQL_ANALYSIS.COMPLETE_STATEMENT_TEXT IS 'Full SQL statement text';
COMMENT ON COLUMN DBM.DBQA_SQL_ANALYSIS.COMPLETE_STATEMENT_HASH IS 'Hash value of the complete SQL statement';
COMMENT ON COLUMN DBM.DBQA_SQL_ANALYSIS.CREATED_BY IS 'User who created the analysis record';
COMMENT ON COLUMN DBM.DBQA_SQL_ANALYSIS.CREATED_TIMESTAMP IS 'When the analysis record was created';
COMMENT ON COLUMN DBM.DBQA_SQL_ANALYSIS.FILE_NAME IS 'Source file name if applicable';
COMMENT ON COLUMN DBM.DBQA_SQL_ANALYSIS.LAST_DDL_TIMESTAMP IS 'When the object was last modified';
COMMENT ON COLUMN DBM.DBQA_SQL_ANALYSIS.LAST_DDL_USER_ID IS 'User who last modified the object';

GRANT CONTROL ON TABLE DBM.DBQA_SQL_ANALYSIS TO FKGEISTA;
GRANT CONTROL ON TABLE DBM.DBQA_SQL_ANALYSIS TO FKSVEERI;
GRANT SELECT ON TABLE DBM.DBQA_SQL_ANALYSIS TO PUBLIC;
CREATE INDEX IDX_DBQA_SQL_APP ON DBM.DBQA_SQL_ANALYSIS(APPLICATION_NAME, ENVIRONMENT_NAME);
COMMIT; 

-- =============================================
-- Statement Analysis Tables
-- =============================================
-- Tables for detailed SQL statement breakdown and analysis
CREATE TABLE DBM.DBQA_STATEMENT_PARTS (
    DBQA_STATEMENT_PARTS_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    DBQA_SQL_ANALYSIS_ID BIGINT NOT NULL,
    STATEMENT_TYPE VARCHAR(50),
    STATEMENT_SUBTYPE VARCHAR(50),
    CAN_CONSUME_OBJECTS SMALLINT,
    STATEMENT_CATEGORY VARCHAR(30),
    STATEMENT_HASH CHAR(64),
    STATEMENT_TEXT VARCHAR(30000),
    LAST_DDL_TIMESTAMP TIMESTAMP,
    LAST_DDL_USER_ID VARCHAR(128),
    PRIMARY KEY (DBQA_STATEMENT_PARTS_ID),
    FOREIGN KEY (DBQA_SQL_ANALYSIS_ID) 
        REFERENCES DBM.DBQA_SQL_ANALYSIS (DBQA_SQL_ANALYSIS_ID)
        ON DELETE CASCADE
);
COMMIT;
COMMENT ON TABLE DBM.DBQA_STATEMENT_PARTS IS 'Detailed breakdown of SQL statements into analyzable components. Enables granular analysis of SQL statement structure and dependencies.';
COMMENT ON COLUMN DBM.DBQA_STATEMENT_PARTS.DBQA_STATEMENT_PARTS_ID IS 'Unique identifier for statement part';
COMMENT ON COLUMN DBM.DBQA_STATEMENT_PARTS.DBQA_SQL_ANALYSIS_ID IS 'Reference to parent SQL analysis record';
COMMENT ON COLUMN DBM.DBQA_STATEMENT_PARTS.STATEMENT_TYPE IS 'Type of SQL statement (SELECT, INSERT, etc)';
COMMENT ON COLUMN DBM.DBQA_STATEMENT_PARTS.STATEMENT_SUBTYPE IS 'Further classification of statement type';
COMMENT ON COLUMN DBM.DBQA_STATEMENT_PARTS.CAN_CONSUME_OBJECTS IS 'Flag indicating if statement references other objects';
COMMENT ON COLUMN DBM.DBQA_STATEMENT_PARTS.STATEMENT_CATEGORY IS 'Category of statement (DML, DDL, etc)';
COMMENT ON COLUMN DBM.DBQA_STATEMENT_PARTS.STATEMENT_HASH IS 'Hash for identifying duplicate statements';
COMMENT ON COLUMN DBM.DBQA_STATEMENT_PARTS.STATEMENT_TEXT IS 'The actual SQL text for this part';
COMMENT ON COLUMN DBM.DBQA_STATEMENT_PARTS.LAST_DDL_TIMESTAMP IS 'When the object''s DDL was last modified';
COMMENT ON COLUMN DBM.DBQA_STATEMENT_PARTS.LAST_DDL_USER_ID IS 'User who last modified the object''s DDL';

GRANT CONTROL ON TABLE DBM.DBQA_STATEMENT_PARTS TO FKGEISTA;
GRANT CONTROL ON TABLE DBM.DBQA_STATEMENT_PARTS TO FKSVEERI;
GRANT SELECT ON TABLE DBM.DBQA_STATEMENT_PARTS TO PUBLIC;
CREATE INDEX IDX_DBQA_STMT_HASH ON DBM.DBQA_STATEMENT_PARTS(STATEMENT_HASH);
COMMIT; 

-- =============================================
-- Object Dependency Tables
-- =============================================
-- Tables for tracking relationships between database objects
CREATE TABLE DBM.DBQA_CONSUMED_OBJECTS (
    DBQA_CONSUMED_OBJECT_ID BIGINT GENERATED ALWAYS AS IDENTITY,
    DBQA_STATEMENT_PARTS_ID BIGINT NOT NULL,
    REFERENCE_OBJECT_SCHEMA_NAME VARCHAR(128) NOT NULL,
    REFERENCE_OBJECT_NAME VARCHAR(128) NOT NULL,
    REFERENCE_OBJECT_TYPE VARCHAR(30) NOT NULL,
    IS_PRIMARY_ELEMENT SMALLINT,
    PRIMARY KEY (DBQA_CONSUMED_OBJECT_ID),
    FOREIGN KEY (DBQA_STATEMENT_PARTS_ID) 
        REFERENCES DBM.DBQA_STATEMENT_PARTS (DBQA_STATEMENT_PARTS_ID)
        ON DELETE CASCADE
);
COMMIT;
COMMENT ON TABLE DBM.DBQA_CONSUMED_OBJECTS IS 'Tracks database objects referenced within SQL statements. Maps relationships and dependencies between database objects for impact analysis.';
COMMENT ON COLUMN DBM.DBQA_CONSUMED_OBJECTS.DBQA_CONSUMED_OBJECT_ID IS 'Unique identifier for consumed object reference';
COMMENT ON COLUMN DBM.DBQA_CONSUMED_OBJECTS.DBQA_STATEMENT_PARTS_ID IS 'Reference to parent statement part';
COMMENT ON COLUMN DBM.DBQA_CONSUMED_OBJECTS.REFERENCE_OBJECT_SCHEMA_NAME IS 'Schema of referenced object';
COMMENT ON COLUMN DBM.DBQA_CONSUMED_OBJECTS.REFERENCE_OBJECT_NAME IS 'Name of referenced object';
COMMENT ON COLUMN DBM.DBQA_CONSUMED_OBJECTS.REFERENCE_OBJECT_TYPE IS 'Type of referenced object (TABLE, VIEW, etc)';
COMMENT ON COLUMN DBM.DBQA_CONSUMED_OBJECTS.IS_PRIMARY_ELEMENT IS 'Flag indicating if this is the main object being accessed';

GRANT CONTROL ON TABLE DBM.DBQA_CONSUMED_OBJECTS TO FKGEISTA;
GRANT CONTROL ON TABLE DBM.DBQA_CONSUMED_OBJECTS TO FKSVEERI;
GRANT SELECT ON TABLE DBM.DBQA_CONSUMED_OBJECTS TO PUBLIC;
CREATE INDEX IDX_DBQA_CONS_REF ON DBM.DBQA_CONSUMED_OBJECTS(REFERENCE_OBJECT_SCHEMA_NAME, REFERENCE_OBJECT_NAME);
COMMIT; 

-- =============================================
-- Package Source Management Tables
-- =============================================
-- Tables for tracking package source files and their status
CREATE TABLE DBM.DBQA_PACKAGE_SOURCE_EXISTENCE (
    PACKAGE_SCHEMA_NAME VARCHAR(128) NOT NULL,
    PACKAGE_NAME VARCHAR(128) NOT NULL,
    INT_FILE VARCHAR(255) NOT NULL,
    SRC_FILE VARCHAR(255),
    OBJECT_NAME VARCHAR(255),
    EXIST_SRC_FILE CHAR(1),
    EXIST_SRC_FILE_IN_DISCARDED_FOLDER CHAR(1),
    PROGRAM_IN_USE CHAR(1),
    COMMENT VARCHAR(255),
    USER VARCHAR(255),
    USED_BY VARCHAR(10000),
    PRIMARY KEY (PACKAGE_SCHEMA_NAME, PACKAGE_NAME)
);
COMMIT;
COMMENT ON TABLE DBM.DBQA_PACKAGE_SOURCE_EXISTENCE IS 'Manages package source file tracking and status. Monitors the existence, location, and usage status of package source files.';
COMMENT ON COLUMN DBM.DBQA_PACKAGE_SOURCE_EXISTENCE.PACKAGE_SCHEMA_NAME IS 'Schema containing the package';
COMMENT ON COLUMN DBM.DBQA_PACKAGE_SOURCE_EXISTENCE.PACKAGE_NAME IS 'Name of the package';
COMMENT ON COLUMN DBM.DBQA_PACKAGE_SOURCE_EXISTENCE.INT_FILE IS 'Internal file reference path or identifier';
COMMENT ON COLUMN DBM.DBQA_PACKAGE_SOURCE_EXISTENCE.SRC_FILE IS 'Path to the source code file';
COMMENT ON COLUMN DBM.DBQA_PACKAGE_SOURCE_EXISTENCE.EXIST_SRC_FILE IS 'Flag indicating if source file exists (Y/N)';
COMMENT ON COLUMN DBM.DBQA_PACKAGE_SOURCE_EXISTENCE.EXIST_SRC_FILE_IN_DISCARDED_FOLDER IS 'Flag indicating if source exists in discarded folder (Y/N)';
COMMENT ON COLUMN DBM.DBQA_PACKAGE_SOURCE_EXISTENCE.PROGRAM_IN_USE IS 'Flag indicating if program is currently in use (Y/N)';
COMMENT ON COLUMN DBM.DBQA_PACKAGE_SOURCE_EXISTENCE.COMMENT IS 'Additional notes or comments about the package';
COMMENT ON COLUMN DBM.DBQA_PACKAGE_SOURCE_EXISTENCE.USER IS 'User associated with the package';
COMMENT ON COLUMN DBM.DBQA_PACKAGE_SOURCE_EXISTENCE.USED_BY IS 'List of programs/objects that use this package';

GRANT CONTROL ON TABLE DBM.DBQA_PACKAGE_SOURCE_EXISTENCE TO FKGEISTA;
GRANT CONTROL ON TABLE DBM.DBQA_PACKAGE_SOURCE_EXISTENCE TO FKSVEERI;
GRANT SELECT ON TABLE DBM.DBQA_PACKAGE_SOURCE_EXISTENCE TO PUBLIC;
CREATE INDEX IDX_DBQA_PKG_SRC ON DBM.DBQA_PACKAGE_SOURCE_EXISTENCE(PACKAGE_SCHEMA_NAME, PACKAGE_NAME);
COMMIT; 

-- =============================================
-- View Usage Analysis Views
-- =============================================
-- Views for analyzing database view usage patterns
CREATE VIEW TV.V_DBQA_VIEWS_NOT_ACCESSED_INTERNALLY AS
WITH VIEWS_USAGE AS (
    -- Get all views from consumed objects
    SELECT DISTINCT 
        REFERENCE_OBJECT_SCHEMA_NAME AS VIEW_SCHEMA,
        REFERENCE_OBJECT_NAME AS VIEW_NAME
    FROM DBM.DBQA_CONSUMED_OBJECTS
    WHERE REFERENCE_OBJECT_TYPE = 'VIEW'
),
ALL_VIEWS AS (
    -- Get all views from system catalog
    SELECT 
        VIEWSCHEMA AS VIEW_SCHEMA,
        VIEWNAME AS VIEW_NAME
    FROM SYSCAT.VIEWS
    WHERE VIEWSCHEMA NOT IN ('SYSCAT', 'SYSIBM', 'SYSSTAT', 'SYSFUN', 'SYSIBMADM')
)
SELECT 
    av.VIEW_SCHEMA,
    av.VIEW_NAME,
    'This view is not referenced in any analyzed SQL' as STATUS
FROM ALL_VIEWS av
LEFT JOIN VIEWS_USAGE vu 
    ON av.VIEW_SCHEMA = vu.VIEW_SCHEMA 
    AND av.VIEW_NAME = vu.VIEW_NAME
WHERE vu.VIEW_NAME IS NULL
AND av.VIEW_SCHEMA IN (SELECT SCHEMA_NAME FROM TV.V_DBQA_SCHEMA_NAME);

COMMENT ON TABLE TV.V_DBQA_VIEWS_NOT_ACCESSED_INTERNALLY IS 'Identifies database views that are not referenced in any analyzed SQL statements, helping identify potentially unused views';
GRANT SELECT ON TV.V_DBQA_VIEWS_NOT_ACCESSED_INTERNALLY TO PUBLIC;
GRANT CONTROL ON TABLE TV.V_DBQA_VIEWS_NOT_ACCESSED_INTERNALLY TO FKGEISTA;
GRANT CONTROL ON TABLE TV.V_DBQA_VIEWS_NOT_ACCESSED_INTERNALLY TO FKSVEERI;
COMMIT;

-- =============================================
-- Migration Planning Views
-- =============================================
-- Views for supporting database migration activities
CREATE VIEW TV.V_DBQA_MIGRATION_TABLES_DB2_115 AS
SELECT 
    X.TABSCHEMA AS SCHEMA_NAME, 
    X.TABNAME AS TABLE_NAME
FROM SYSCAT.TABLES X
WHERE x.LASTUSED > DATE(CURRENT TIMESTAMP - 3 YEARS)AND x.TYPE IN ('T')
AND X.TABSCHEMA IN (SELECT SCHEMA_NAME FROM TV.V_DBQA_SCHEMA_NAME);

COMMENT ON TABLE TV.V_DBQA_MIGRATION_TABLES_DB2_115 IS 'Lists tables that have been accessed within the last 3 years, useful for DB2 v11.5 migration planning';
GRANT SELECT ON TV.V_DBQA_MIGRATION_TABLES_DB2_115 TO PUBLIC;
GRANT CONTROL ON TABLE TV.V_DBQA_MIGRATION_TABLES_DB2_115 TO FKGEISTA;
GRANT CONTROL ON TABLE TV.V_DBQA_MIGRATION_TABLES_DB2_115 TO FKSVEERI;
COMMIT;

-- =============================================
-- Source Code Management Views
-- =============================================
-- Views for tracking and validating source code
CREATE VIEW TV.V_DBQA_PACKAGE_MISSING_CBL_SOURCE AS
SELECT y.*
FROM DBM.DBQA_PACKAGE_SOURCE_EXISTENCE y
WHERE Y.PROGRAM_IN_USE = 'Y'
AND EXIST_SRC_FILE = 'N';

COMMENT ON TABLE TV.V_DBQA_PACKAGE_MISSING_CBL_SOURCE IS 'Identifies active packages that are missing their COBOL source files, helping track source code management issues';
GRANT SELECT ON TV.V_DBQA_PACKAGE_MISSING_CBL_SOURCE TO PUBLIC;
GRANT CONTROL ON TABLE TV.V_DBQA_PACKAGE_MISSING_CBL_SOURCE TO FKGEISTA;
GRANT CONTROL ON TABLE TV.V_DBQA_PACKAGE_MISSING_CBL_SOURCE TO FKSVEERI;
COMMIT;

-- =============================================
-- Package Usage Analysis Views
-- =============================================
-- Views for analyzing package usage patterns
CREATE OR REPLACE VIEW TV.V_UNUSED_PACKAGES_ANALYSIS AS
WITH PACKAGE_TABLES AS (
    -- Get all tables referenced by each package through DBQA tables
    SELECT DISTINCT 
        dsa.SOURCE_SCHEMA_NAME AS PACKAGE_SCHEMA_NAME,
        dsa.SOURCE_NAME AS PACKAGE_NAME,
        dco.REFERENCE_OBJECT_SCHEMA_NAME AS TABLE_SCHEMA,
        dco.REFERENCE_OBJECT_NAME AS TABLE_NAME
    FROM DBM.DBQA_SQL_ANALYSIS dsa
    JOIN DBM.DBQA_STATEMENT_PARTS dsp ON dsa.DBQA_SQL_ANALYSIS_ID = dsp.DBQA_SQL_ANALYSIS_ID
    JOIN DBM.DBQA_CONSUMED_OBJECTS dco ON dsp.DBQA_STATEMENT_PARTS_ID = dco.DBQA_STATEMENT_PARTS_ID
    WHERE dco.REFERENCE_OBJECT_TYPE = 'TABLE'
    AND dsa.OBJECT_TYPE = 'PACKAGE'
),
TABLE_USAGE AS (
    -- Get last usage information for tables
    SELECT 
        PACKAGE_SCHEMA_NAME,
        PT.PACKAGE_NAME,
        PT.TABLE_SCHEMA,
        PT.TABLE_NAME,
        T.LASTUSED
    FROM PACKAGE_TABLES PT
    JOIN SYSCAT.TABLES T 
        ON PT.TABLE_SCHEMA = T.TABSCHEMA 
        AND PT.TABLE_NAME = T.TABNAME
),
PACKAGE_LAST_USAGE AS (
    -- Get the most recent LASTUSED date for each package's tables
    SELECT 
        PACKAGE_SCHEMA_NAME,
        PACKAGE_NAME,
        MAX(LASTUSED) AS MOST_RECENT_TABLE_USAGE
    FROM TABLE_USAGE
    GROUP BY PACKAGE_SCHEMA_NAME, PACKAGE_NAME
)
SELECT 
    p.PACKAGE_SCHEMA_NAME,
    p.PACKAGE_NAME,
    p.MOST_RECENT_TABLE_USAGE,
    CASE 
        WHEN p.MOST_RECENT_TABLE_USAGE IS NULL THEN 'No usage data available'
        ELSE 'Last table usage was ' || CAST(DAY(CURRENT DATE - DATE(p.MOST_RECENT_TABLE_USAGE)) AS VARCHAR(10)) || ' days ago'
    END AS STATUS,
    pse.PROGRAM_IN_USE,
    pse.COMMENT,
    pse.USED_BY,
    'Unused based on table access' as DETECTION_METHOD,
    CASE WHEN p.MOST_RECENT_TABLE_USAGE IS NULL THEN 1 ELSE 2 END as SORT_NULL_FIRST,
    COALESCE(p.MOST_RECENT_TABLE_USAGE, DATE('9999-12-31')) as SORT_DATE
FROM PACKAGE_LAST_USAGE p
LEFT JOIN DBM.DBQA_PACKAGE_SOURCE_EXISTENCE pse 
    ON p.PACKAGE_SCHEMA_NAME = pse.PACKAGE_SCHEMA_NAME AND p.PACKAGE_NAME = pse.PACKAGE_NAME
WHERE (p.MOST_RECENT_TABLE_USAGE < CURRENT DATE - 3 YEARS
    OR p.MOST_RECENT_TABLE_USAGE IS NULL)
    AND (pse.PROGRAM_IN_USE IS NULL OR pse.PROGRAM_IN_USE != 'Y')

UNION

SELECT 
    PACKAGE_SCHEMA_NAME,
    PACKAGE_NAME,
    NULL as MOST_RECENT_TABLE_USAGE,
    'Explicitly marked as not in use' as STATUS,
    PROGRAM_IN_USE,
    COMMENT,
    USED_BY,
    'Marked as not in use (PROGRAM_IN_USE = ''N'')' as DETECTION_METHOD,
    1 as SORT_NULL_FIRST,
    DATE('9999-12-31') as SORT_DATE
FROM DBM.DBQA_PACKAGE_SOURCE_EXISTENCE
WHERE PROGRAM_IN_USE = 'N';

COMMENT ON TABLE TV.V_UNUSED_PACKAGES_ANALYSIS IS 'Analyzes package usage patterns based on table access history and explicit usage flags to identify potentially unused packages';
GRANT SELECT ON TV.V_UNUSED_PACKAGES_ANALYSIS TO PUBLIC;
GRANT CONTROL ON TABLE TV.V_UNUSED_PACKAGES_ANALYSIS TO FKGEISTA;
GRANT CONTROL ON TABLE TV.V_UNUSED_PACKAGES_ANALYSIS TO FKSVEERI;
COMMIT;

-- =============================================
-- Statement Validation Views
-- =============================================
-- Views for validating SQL statement consistency
CREATE OR REPLACE VIEW tv.V_DBQA_STATEMENT_PARTS_HASH_CHK AS
    SELECT dsp.STATEMENT_HASH,
       COUNT(DISTINCT dsp.STATEMENT_TYPE) AS Unique_Statement_Types,
       COUNT(DISTINCT dsp.STATEMENT_SUBTYPE) AS Unique_Statement_Subtypes,
       COUNT(DISTINCT dsp.STATEMENT_CATEGORY) AS Unique_Statement_Categories,
       COUNT(DISTINCT dsp.STATEMENT_TEXT) AS Unique_Statement_Texts
FROM dbm.DBQA_STATEMENT_PARTS dsp
JOIN dbm.DBQA_SQL_ANALYSIS dsa
ON dsp.DBQA_SQL_ANALYSIS_ID = dsa.DBQA_SQL_ANALYSIS_ID
WHERE dsa.APPLICATION_NAME = 'FKM'
GROUP BY dsp.STATEMENT_HASH
HAVING COUNT(DISTINCT dsp.STATEMENT_TYPE) > 1
    OR COUNT(DISTINCT dsp.STATEMENT_SUBTYPE) > 1
    OR COUNT(DISTINCT dsp.STATEMENT_CATEGORY) > 1
    OR COUNT(DISTINCT dsp.STATEMENT_TEXT) > 1;

COMMENT ON TABLE TV.V_DBQA_STATEMENT_PARTS_HASH_CHK IS 'Validates statement hash consistency by identifying cases where identical hashes have different statement characteristics';
GRANT SELECT ON TV.V_DBQA_STATEMENT_PARTS_HASH_CHK TO PUBLIC;
GRANT CONTROL ON TABLE TV.V_DBQA_STATEMENT_PARTS_HASH_CHK TO FKGEISTA;
GRANT CONTROL ON TABLE TV.V_DBQA_STATEMENT_PARTS_HASH_CHK TO FKSVEERI;
COMMIT;

-- =============================================
-- Source Code Comparison Views
-- =============================================
-- Views for comparing source code across environments
CREATE OR REPLACE VIEW tv.V_DBQA_SOURCE_DIFFERENCES AS
SELECT  
    x.APPLICATION_NAME, 
    x.OBJECT_NAME, 
    x.OBJECT_TYPE,    
    LISTAGG(DSA.ENVIRONMENT_NAME, ', ') WITHIN GROUP (ORDER BY DSA.ENVIRONMENT_NAME) AS ENVIRONMENTS,
    LISTAGG(DSA.LAST_DDL_TIMESTAMP, ', ') WITHIN GROUP (ORDER BY DSA.ENVIRONMENT_NAME) AS LAST_DDL_TIMESTAMPS,
    LISTAGG(DSA.LAST_DDL_USER_ID, ', ') WITHIN GROUP (ORDER BY DSA.ENVIRONMENT_NAME) AS LAST_DDL_USER_IDS
FROM 
    DBM.DBQA_SQL_ANALYSIS DSA
JOIN 
    (SELECT DISTINCT DSA.APPLICATION_NAME, 
        DSA.OBJECT_NAME, 
        DSA.OBJECT_TYPE
    FROM
        (SELECT 
            DSA.APPLICATION_NAME, 
            DSA.OBJECT_NAME, 
            DSA.OBJECT_TYPE,
            DSP.STATEMENT_TYPE,
            DSP.STATEMENT_SUBTYPE,
            DSP.STATEMENT_CATEGORY,
            COUNT(DISTINCT DSP.STATEMENT_HASH) AS distinct_statement_hashes
        FROM 
            DBM.DBQA_STATEMENT_PARTS DSP
        JOIN 
            DBM.DBQA_SQL_ANALYSIS DSA
        ON 
            DSP.DBQA_SQL_ANALYSIS_ID = DSA.DBQA_SQL_ANALYSIS_ID
        WHERE 
            DSA.APPLICATION_NAME = 'FKM'
            AND DSA.OBJECT_TYPE <> 'BIND.SQL'
        GROUP BY 
            DSA.APPLICATION_NAME, 
            DSA.OBJECT_NAME, 
            DSA.OBJECT_TYPE, 
            DSP.STATEMENT_TYPE,
            DSP.STATEMENT_SUBTYPE,
            DSP.STATEMENT_CATEGORY
        HAVING 
            COUNT(DISTINCT DSP.STATEMENT_HASH) > 1
        ) DSA
    ) x
ON 
    DSA.APPLICATION_NAME = x.APPLICATION_NAME
    AND DSA.OBJECT_NAME = x.OBJECT_NAME
    AND DSA.OBJECT_TYPE = x.OBJECT_TYPE
WHERE 
    DSA.APPLICATION_NAME = 'FKM'
    AND DSA.OBJECT_TYPE <> 'BIND.SQL'    
GROUP BY
    x.APPLICATION_NAME, 
    x.OBJECT_NAME, 
    x.OBJECT_TYPE;

COMMENT ON TABLE TV.V_DBQA_SOURCE_DIFFERENCES IS 'Compares source code differences across environments by analyzing statement hashes and DDL timestamps';
GRANT SELECT ON TV.V_DBQA_SOURCE_DIFFERENCES TO PUBLIC;
GRANT CONTROL ON TABLE TV.V_DBQA_SOURCE_DIFFERENCES TO FKGEISTA;
GRANT CONTROL ON TABLE TV.V_DBQA_SOURCE_DIFFERENCES TO FKSVEERI;
COMMIT;

GRANT CONTROL ON SCHEMA DBM TO GROUP DB2ADMNS;
GRANT CONTROL ON SCHEMA TV TO GROUP DB2ADMNS;
GRANT SELECT ON ALL TABLES IN SCHEMA DBM TO GROUP DB2ADMNS;
GRANT SELECT ON ALL TABLES IN SCHEMA TV TO GROUP DB2ADMNS;
COMMIT;
