Traceback (most recent call last):
  File "D:\opt\src\SqlMermaidErdTools\src\SqlMermaidErdTools\runtimes\win-x64\scripts\sql_to_mmd.py", line 278, in <module>
    def extract_alter_table_foreign_key(alter_statement: exp.AlterTable) -> Dict[str, Any]:
                                                         ^^^^^^^^^^^^^^
AttributeError: module 'sqlglot.expressions' has no attribute 'AlterTable'

