# Author: Geir Helge Starholm, www.dEdge.no
# Title: AutoDoc IIS Local Deployment
# Description: Sets up IIS to host AutoDoc static site as a subfolder under Default Web Site
#              Creates virtual application at /AutoDoc pointing to the content folder
#              Configures Windows Authentication for secure access (domain users only)
#              Supports full teardown/recreate while preserving static assets

param(
    # Deployment method
    [Parameter(Mandatory = $false)]
    [ValidateSet("Deploy", "Teardown", "Redeploy", "Status")]
    [string]$Action = "Deploy",
    
    # Clean generated files during redeploy (preserves .js, .css, .images, .json, .templates, index.html)
    [switch]$CleanGeneratedFiles,
    
    # Skip IIS installation check (faster for repeated deployments)
    [switch]$SkipIISCheck,
    
    # Content folder path (default: $env:OptPath\Webs\AutoDoc)
    [string]$ContentPath = "$env:OptPath\Webs\AutoDoc"
)

Import-Module GlobalFunctions -Force

# =============================================================================
# AutoDoc IIS Deployment Script
# =============================================================================
#
# PURPOSE:
#   Creates a virtual application under IIS Default Web Site to host AutoDoc
#   static content (HTML documentation generated by AutoDocBatchRunner.ps1)
#
# ACTIONS:
#   - Deploy:    Set up IIS virtual application /AutoDoc (idempotent)
#   - Teardown:  Remove the virtual application from IIS
#   - Redeploy:  Full teardown + deploy (optionally clean generated files)
#   - Status:    Show current deployment status
#
# URL AFTER DEPLOYMENT:
#   http://localhost/AutoDoc/
#   http://<servername>/AutoDoc/
#
# CONTENT LOCATION:
#   $env:OptPath\Webs\AutoDoc (default)
#   - index.html (main entry point)
#   - .js/, .css/, .images/ (static assets - preserved during clean)
#   - .json/ (parser result JSON files)
#   - *.html (generated documentation files)
#
# =============================================================================

#region Configuration

$AppName = "AutoDoc"
$AppPoolName = "AutoDocAppPool"
$DefaultWebSite = "Default Web Site"

# Folders to preserve during CleanGeneratedFiles (static assets)
$preserveFolders = @(".js", ".css", ".images", ".json", "_templates")
$preserveFiles = @("index.html", "web.config")

#endregion Configuration

#region Helper Functions

function Test-IISInstalled {
    <#
    .SYNOPSIS
        Checks if IIS is installed using appcmd.exe
    #>
    try {
        # Check if appcmd.exe exists (IIS is installed)
        $appcmdPath = "$env:SystemRoot\System32\inetsrv\appcmd.exe"
        if (Test-Path $appcmdPath) {
            return $true
        }
        
        # Fallback: Check if W3SVC service exists
        $w3svc = Get-Service -Name W3SVC -ErrorAction SilentlyContinue
        if ($w3svc) {
            return $true
        }
        
        return $false
    }
    catch {
        return $false
    }
}

# IIS command-line tool path
$script:AppCmd = "$env:SystemRoot\System32\inetsrv\appcmd.exe"

function Test-AppCmdAvailable {
    <#
    .SYNOPSIS
        Checks if appcmd.exe is available (IIS is installed)
    #>
    return (Test-Path $script:AppCmd)
}

function Invoke-AppCmd {
    <#
    .SYNOPSIS
        Runs appcmd.exe with arguments and returns output
    #>
    param(
        [Parameter(Mandatory)]
        [string[]]$Arguments
    )
    
    $result = & $script:AppCmd @Arguments 2>&1
    return $result
}

function Install-IISIfNeeded {
    <#
    .SYNOPSIS
        Installs IIS and required features if not already installed
        Self-healing: retries and waits for IIS to become available
    #>
    Write-LogMessage "Checking IIS installation..." -Level INFO
    
    if (Test-IISInstalled) {
        Write-LogMessage "IIS is already installed" -Level INFO
        return $true
    }
    
    Write-LogMessage "Installing IIS and required features..." -Level INFO
    
    try {
        # Core IIS features for static file hosting with Windows Authentication
        $features = @(
            "IIS-WebServer",
            "IIS-WebServerRole",
            "IIS-CommonHttpFeatures",
            "IIS-StaticContent",
            "IIS-DefaultDocument",
            "IIS-DirectoryBrowsing",
            "IIS-HttpErrors",
            "IIS-HttpLogging",
            "IIS-RequestFiltering",
            "IIS-ManagementConsole",
            "IIS-ManagementScriptingTools",
            "IIS-WindowsAuthentication"  # Required for Windows Authentication
        )
        
        # Check which features need to be installed (skip already enabled)
        $featuresToInstall = @()
        foreach ($feature in $features) {
            $featureState = Get-WindowsOptionalFeature -Online -FeatureName $feature -ErrorAction SilentlyContinue
            if ($featureState -and $featureState.State -eq "Enabled") {
                Write-LogMessage "Feature already installed: $feature" -Level INFO
            }
            else {
                $featuresToInstall += $feature
            }
        }
        
        if ($featuresToInstall.Count -eq 0) {
            Write-LogMessage "All IIS features are already installed" -Level INFO
        }
        else {
            Write-LogMessage "Installing $($featuresToInstall.Count) missing IIS features..." -Level INFO
            foreach ($feature in $featuresToInstall) {
                Write-LogMessage "Installing feature: $feature" -Level INFO
                $result = Enable-WindowsOptionalFeature -Online -FeatureName $feature -All -NoRestart -ErrorAction SilentlyContinue
                if (-not $result) {
                    Write-LogMessage "Feature $feature installation returned no result (may require elevation)" -Level WARN
                }
            }
        }
        
        # Start W3SVC service if it exists but isn't running
        Write-LogMessage "Ensuring IIS service (W3SVC) is started..." -Level INFO
        $w3svc = Get-Service -Name W3SVC -ErrorAction SilentlyContinue
        if ($w3svc -and $w3svc.Status -ne 'Running') {
            Start-Service -Name W3SVC -ErrorAction SilentlyContinue
            Start-Sleep -Seconds 2
        }
        
        # Self-healing: retry checking IIS installation with delays
        $maxRetries = 5
        $retryDelay = 3
        for ($i = 1; $i -le $maxRetries; $i++) {
            Write-LogMessage "Verifying IIS installation (attempt $($i)/$($maxRetries))..." -Level INFO
            Start-Sleep -Seconds $retryDelay
            
            if (Test-IISInstalled) {
                Write-LogMessage "IIS installation completed successfully" -Level INFO
                return $true
            }
            
            # Progressive delay increase
            $retryDelay = [Math]::Min($retryDelay + 2, 10)
        }
        
        # Final fallback: check if W3SVC is running - IIS might work even if module detection is flaky
        $w3svc = Get-Service -Name W3SVC -ErrorAction SilentlyContinue
        if ($w3svc -and $w3svc.Status -eq 'Running') {
            Write-LogMessage "IIS service is running - proceeding despite module detection issues" -Level WARN
            return $true
        }
        
        Write-LogMessage "IIS installation may require a system restart" -Level WARN
        return $false
    }
    catch {
        Write-LogMessage "Failed to install IIS: $($_.Exception.Message)" -Level ERROR -Exception $_
        return $false
    }
}

function Get-AutoDocDeploymentStatus {
    <#
    .SYNOPSIS
        Returns the current deployment status of AutoDoc in IIS (uses appcmd.exe)
    #>
    $status = [PSCustomObject]@{
        IISInstalled      = $false
        AppPoolExists     = $false
        AppPoolRunning    = $false
        AppExists         = $false
        ContentPathExists = $false
        ContentFileCount  = 0
        AccessUrl         = $null
    }
    
    try {
        # Check if appcmd is available (IIS installed)
        if (-not (Test-AppCmdAvailable)) {
            return $status
        }
        $status.IISInstalled = $true
        
        # Check app pool using appcmd
        $poolResult = Invoke-AppCmd @("list", "apppool", $AppPoolName)
        if ($poolResult -and $poolResult -notmatch "ERROR") {
            $status.AppPoolExists = $true
            # Check if pool is started
            $poolState = Invoke-AppCmd @("list", "apppool", $AppPoolName, "/text:state")
            $status.AppPoolRunning = ($poolState -eq "Started")
        }
        
        # Check virtual application using appcmd
        $appResult = Invoke-AppCmd @("list", "app", "/site.name:$DefaultWebSite", "/path:/$AppName")
        if ($appResult -and $appResult -notmatch "ERROR") {
            $status.AppExists = $true
        }
        
        # Check content
        if (Test-Path $ContentPath) {
            $status.ContentPathExists = $true
            $status.ContentFileCount = (Get-ChildItem -Path $ContentPath -Filter "*.html" -File -ErrorAction SilentlyContinue).Count
        }
        
        # Determine URL
        if ($status.AppExists) {
            $status.AccessUrl = "http://localhost/$AppName/"
        }
    }
    catch {
        # IIS not installed or appcmd failed
    }
    
    return $status
}

function New-AutoDocAppPool {
    <#
    .SYNOPSIS
        Creates the AutoDoc application pool for static content (uses appcmd.exe)
    #>
    Write-LogMessage "Creating application pool: $AppPoolName" -Level INFO
    
    try {
        # Check if pool already exists
        $poolResult = Invoke-AppCmd @("list", "apppool", $AppPoolName)
        if ($poolResult -and $poolResult -notmatch "ERROR") {
            Write-LogMessage "Application pool already exists, removing..." -Level INFO
            Invoke-AppCmd @("delete", "apppool", $AppPoolName) | Out-Null
            Start-Sleep -Seconds 1
        }
        
        # Create new app pool with settings optimized for static content
        # managedRuntimeVersion="" means no managed code (static files only)
        # processModel.identityType=ApplicationPoolIdentity uses the standard IIS default identity
        $createResult = Invoke-AppCmd @("add", "apppool", "/name:$AppPoolName", "/managedRuntimeVersion:", "/managedPipelineMode:Integrated", "/processModel.identityType:ApplicationPoolIdentity")
        if ($createResult -match "ERROR") {
            throw "Failed to create app pool: $createResult"
        }
        
        # Start the pool
        Invoke-AppCmd @("start", "apppool", $AppPoolName) | Out-Null
        
        Write-LogMessage "Application pool created and started" -Level INFO
        return $true
    }
    catch {
        Write-LogMessage "Failed to create application pool: $($_.Exception.Message)" -Level ERROR -Exception $_
        return $false
    }
}

function Set-IISContentPermissions {
    <#
    .SYNOPSIS
        Sets the correct file system permissions for IIS to access the content folder
        Adds Read & Execute permissions for IIS_IUSRS, IUSR, and SYSTEM
    #>
    param(
        [Parameter(Mandatory)]
        [string]$Path
    )
    
    Write-LogMessage "Setting IIS permissions on: $Path" -Level INFO
    
    try {
        if (-not (Test-Path $Path)) {
            Write-LogMessage "Path does not exist, creating: $Path" -Level INFO
            New-Item -ItemType Directory -Path $Path -Force | Out-Null
        }
        
        # Get current ACL
        $acl = Get-Acl -Path $Path
        
        # Define the accounts that need access
        $accounts = @(
            "IIS_IUSRS",           # IIS worker process group
            "IUSR",                # Anonymous authentication user
            "NT AUTHORITY\SYSTEM"  # System account
        )
        
        # Permission: Read & Execute, List folder contents, Read
        $rights = [System.Security.AccessControl.FileSystemRights]::ReadAndExecute -bor `
                  [System.Security.AccessControl.FileSystemRights]::ListDirectory -bor `
                  [System.Security.AccessControl.FileSystemRights]::Read
        
        $inheritanceFlags = [System.Security.AccessControl.InheritanceFlags]::ContainerInherit -bor `
                            [System.Security.AccessControl.InheritanceFlags]::ObjectInherit
        $propagationFlags = [System.Security.AccessControl.PropagationFlags]::None
        $accessType = [System.Security.AccessControl.AccessControlType]::Allow
        
        foreach ($account in $accounts) {
            try {
                $accessRule = New-Object System.Security.AccessControl.FileSystemAccessRule(
                    $account, $rights, $inheritanceFlags, $propagationFlags, $accessType
                )
                $acl.AddAccessRule($accessRule)
                Write-LogMessage "Added Read & Execute permission for: $account" -Level INFO
            }
            catch {
                Write-LogMessage "Could not add permission for $($account): $($_.Exception.Message)" -Level WARN
            }
        }
        
        # Apply the ACL
        Set-Acl -Path $Path -AclObject $acl -ErrorAction Stop
        Write-LogMessage "IIS permissions applied successfully" -Level INFO
        return $true
    }
    catch {
        Write-LogMessage "Failed to set IIS permissions: $($_.Exception.Message)" -Level ERROR -Exception $_
        return $false
    }
}

function New-AutoDocVirtualApp {
    <#
    .SYNOPSIS
        Creates the AutoDoc virtual application under Default Web Site (uses appcmd.exe)
    #>
    Write-LogMessage "Creating virtual application: /$AppName" -Level INFO
    
    try {
        # Ensure content path exists
        if (-not (Test-Path $ContentPath)) {
            Write-LogMessage "Creating content folder: $ContentPath" -Level INFO
            New-Item -ItemType Directory -Path $ContentPath -Force | Out-Null
        }
        
        # Check if application already exists
        $appResult = Invoke-AppCmd @("list", "app", "/site.name:$DefaultWebSite", "/path:/$AppName")
        if ($appResult -and $appResult -notmatch "ERROR") {
            Write-LogMessage "Virtual application already exists, removing..." -Level INFO
            Invoke-AppCmd @("delete", "app", "$DefaultWebSite/$AppName") | Out-Null
            Start-Sleep -Seconds 1
        }
        
        # Create virtual application
        # appcmd add app /site.name:"Default Web Site" /path:/AutoDoc /physicalPath:E:\opt\Webs\AutoDoc /applicationPool:AutoDocAppPool
        $createResult = Invoke-AppCmd @("add", "app", "/site.name:$DefaultWebSite", "/path:/$AppName", "/physicalPath:$ContentPath", "/applicationPool:$AppPoolName")
        if ($createResult -match "ERROR") {
            throw "Failed to create app: $createResult"
        }
        
        Write-LogMessage "Virtual application created at /$AppName" -Level INFO
        
        # Enable directory browsing using appcmd
        Invoke-AppCmd @("set", "config", "$DefaultWebSite/$AppName", "/section:directoryBrowse", "/enabled:true") | Out-Null
        
        Write-LogMessage "Virtual application configured successfully" -Level INFO
        return $true
    }
    catch {
        Write-LogMessage "Failed to create virtual application: $($_.Exception.Message)" -Level ERROR -Exception $_
        return $false
    }
}

function Set-AutoDocMimeTypes {
    <#
    .SYNOPSIS
        Configures MIME types for AutoDoc content using appcmd.exe
        Note: Most MIME types (.json, .svg, .woff, .woff2) are already configured in IIS by default
    #>
    Write-LogMessage "Configuring MIME types..." -Level INFO
    
    try {
        # Custom MIME types for AutoDoc (only .mmd needs to be added, others are IIS defaults)
        $mimeTypes = @(
            @{ Extension = ".mmd"; MimeType = "text/plain" }
        )
        
        foreach ($mime in $mimeTypes) {
            try {
                # Add MIME type at the application level using appcmd
                # appcmd set config "Default Web Site/AutoDoc" /section:staticContent /+"[fileExtension='.mmd',mimeType='text/plain']"
                $result = Invoke-AppCmd @("set", "config", "$DefaultWebSite/$AppName", "/section:staticContent", "/+`"[fileExtension='$($mime.Extension)',mimeType='$($mime.MimeType)']`"")
                if ($result -notmatch "ERROR") {
                    Write-LogMessage "Added MIME type: $($mime.Extension) -> $($mime.MimeType)" -Level INFO
                }
            }
            catch {
                # MIME type might already exist
            }
        }
        
        Write-LogMessage "MIME types configured" -Level INFO
        return $true
    }
    catch {
        Write-LogMessage "Failed to configure MIME types: $($_.Exception.Message)" -Level WARN
        return $false
    }
}

function Set-AutoDocWindowsAuthentication {
    <#
    .SYNOPSIS
        Configures Windows Authentication for AutoDoc virtual application
        Disables anonymous authentication and enables Windows authentication
        This provides seamless SSO for domain users
    #>
    Write-LogMessage "Configuring Windows Authentication..." -Level INFO
    
    try {
        # Disable anonymous authentication
        # appcmd set config "Default Web Site/AutoDoc" /section:anonymousAuthentication /enabled:false
        $result = Invoke-AppCmd @("set", "config", "$DefaultWebSite/$AppName", "/section:anonymousAuthentication", "/enabled:false")
        if ($result -match "ERROR") {
            Write-LogMessage "Warning: Could not disable anonymous auth: $result" -Level WARN
        }
        else {
            Write-LogMessage "Disabled anonymous authentication" -Level INFO
        }
        
        # Enable Windows authentication
        # appcmd set config "Default Web Site/AutoDoc" /section:windowsAuthentication /enabled:true
        $result = Invoke-AppCmd @("set", "config", "$DefaultWebSite/$AppName", "/section:windowsAuthentication", "/enabled:true")
        if ($result -match "ERROR") {
            Write-LogMessage "Warning: Could not enable Windows auth: $result" -Level WARN
            Write-LogMessage "Windows Authentication feature may not be installed" -Level WARN
            return $false
        }
        else {
            Write-LogMessage "Enabled Windows authentication" -Level INFO
        }
        
        Write-LogMessage "Windows Authentication configured successfully" -Level INFO
        Write-LogMessage "Users will authenticate with their Windows/domain credentials" -Level INFO
        return $true
    }
    catch {
        Write-LogMessage "Failed to configure Windows Authentication: $($_.Exception.Message)" -Level WARN
        Write-LogMessage "Falling back to anonymous authentication" -Level WARN
        return $false
    }
}

function Remove-AutoDocDeployment {
    <#
    .SYNOPSIS
        Removes the AutoDoc virtual application and app pool from IIS (uses appcmd.exe)
    #>
    Write-LogMessage "Tearing down AutoDoc IIS deployment..." -Level INFO
    
    try {
        # Remove virtual application
        $appResult = Invoke-AppCmd @("list", "app", "/site.name:$DefaultWebSite", "/path:/$AppName")
        if ($appResult -and $appResult -notmatch "ERROR") {
            Write-LogMessage "Removing virtual application: /$AppName" -Level INFO
            Invoke-AppCmd @("delete", "app", "$DefaultWebSite/$AppName") | Out-Null
        }
        else {
            Write-LogMessage "Virtual application not found (already removed)" -Level INFO
        }
        
        # Stop and remove app pool
        $poolResult = Invoke-AppCmd @("list", "apppool", $AppPoolName)
        if ($poolResult -and $poolResult -notmatch "ERROR") {
            Write-LogMessage "Stopping and removing application pool: $AppPoolName" -Level INFO
            
            # Stop the pool first
            Invoke-AppCmd @("stop", "apppool", $AppPoolName) 2>$null | Out-Null
            Start-Sleep -Seconds 2
            
            # Delete the pool
            Invoke-AppCmd @("delete", "apppool", $AppPoolName) | Out-Null
        }
        else {
            Write-LogMessage "Application pool not found (already removed)" -Level INFO
        }
        
        Write-LogMessage "Teardown completed" -Level INFO
        return $true
    }
    catch {
        Write-LogMessage "Failed to teardown: $($_.Exception.Message)" -Level ERROR -Exception $_
        return $false
    }
}

function Clear-AutoDocGeneratedFiles {
    <#
    .SYNOPSIS
        Removes generated files from the content folder while preserving static assets
        Preserves: .js/, .css/, .images/, .json/, .templates/ folders and index.html
    #>
    Write-LogMessage "Cleaning generated files from content folder..." -Level INFO
    Write-LogMessage "  Preserving folders: $($preserveFolders -join ', ')" -Level INFO
    Write-LogMessage "  Preserving files: $($preserveFiles -join ', ')" -Level INFO
    
    if (-not (Test-Path $ContentPath)) {
        Write-LogMessage "Content folder does not exist: $ContentPath" -Level WARN
        return $true
    }
    
    try {
        # Remove all .html files except preserved ones
        $htmlFiles = Get-ChildItem -Path $ContentPath -Filter "*.html" -File -ErrorAction SilentlyContinue | 
            Where-Object { $_.Name -notin $preserveFiles }
        if ($htmlFiles) {
            $htmlFiles | Remove-Item -Force -ErrorAction SilentlyContinue
            Write-LogMessage "  Removed $($htmlFiles.Count) HTML files (kept: $($preserveFiles -join ', '))" -Level INFO
        }
        
        # Remove all .mmd files (Mermaid source)
        $mmdFiles = Get-ChildItem -Path $ContentPath -Filter "*.mmd" -File -ErrorAction SilentlyContinue
        if ($mmdFiles) {
            $mmdFiles | Remove-Item -Force -ErrorAction SilentlyContinue
            Write-LogMessage "  Removed $($mmdFiles.Count) MMD files" -Level INFO
        }
        
        # Remove all .err files (error logs)
        $errFiles = Get-ChildItem -Path $ContentPath -Filter "*.err" -File -ErrorAction SilentlyContinue
        if ($errFiles) {
            $errFiles | Remove-Item -Force -ErrorAction SilentlyContinue
            Write-LogMessage "  Removed $($errFiles.Count) ERR files" -Level INFO
        }
        
        Write-LogMessage "Generated files cleaned" -Level INFO
        return $true
    }
    catch {
        Write-LogMessage "Failed to clean generated files: $($_.Exception.Message)" -Level ERROR -Exception $_
        return $false
    }
}

function Show-DeploymentStatus {
    <#
    .SYNOPSIS
        Displays the current deployment status
    #>
    $status = Get-AutoDocDeploymentStatus
    
    Write-Host ""
    Write-Host "═══════════════════════════════════════════════════════════" -ForegroundColor Cyan
    Write-Host "   AutoDoc IIS Deployment Status" -ForegroundColor Cyan
    Write-Host "═══════════════════════════════════════════════════════════" -ForegroundColor Cyan
    Write-Host ""
    
    $iisStatus = if ($status.IISInstalled) { "✓ Installed" } else { "✗ Not Installed" }
    $iisColor = if ($status.IISInstalled) { "Green" } else { "Red" }
    Write-Host "  IIS:              " -NoNewline; Write-Host $iisStatus -ForegroundColor $iisColor
    
    $poolStatus = if ($status.AppPoolExists) { 
        if ($status.AppPoolRunning) { "✓ Running" } else { "⚠ Stopped" }
    } else { "✗ Not Created" }
    $poolColor = if ($status.AppPoolRunning) { "Green" } elseif ($status.AppPoolExists) { "Yellow" } else { "Red" }
    Write-Host "  App Pool:         " -NoNewline; Write-Host $poolStatus -ForegroundColor $poolColor
    
    $appStatus = if ($status.AppExists) { "✓ Configured" } else { "✗ Not Configured" }
    $appColor = if ($status.AppExists) { "Green" } else { "Red" }
    Write-Host "  Virtual App:      " -NoNewline; Write-Host $appStatus -ForegroundColor $appColor
    
    $contentStatus = if ($status.ContentPathExists) { "✓ Exists ($($status.ContentFileCount) HTML files)" } else { "✗ Missing" }
    $contentColor = if ($status.ContentPathExists) { "Green" } else { "Red" }
    Write-Host "  Content Path:     " -NoNewline; Write-Host $contentStatus -ForegroundColor $contentColor
    
    Write-Host ""
    Write-Host "  Content Folder:   $ContentPath" -ForegroundColor Gray
    
    if ($status.AccessUrl) {
        Write-Host ""
        Write-Host "  Access URL:       " -NoNewline; Write-Host $status.AccessUrl -ForegroundColor Green
    }
    
    Write-Host ""
    Write-Host "═══════════════════════════════════════════════════════════" -ForegroundColor Cyan
    Write-Host ""
    
    return $status
}

#endregion Helper Functions

#region Main Execution

Write-LogMessage "AutoDoc IIS Deployment - Action: $Action" -Level INFO
Write-LogMessage "Content Path: $ContentPath" -Level INFO

switch ($Action) {
    "Status" {
        Show-DeploymentStatus
    }
    
    "Teardown" {
        if (-not (Test-IISInstalled)) {
            Write-LogMessage "IIS is not installed, nothing to tear down" -Level WARN
            exit 0
        }
        
        $result = Remove-AutoDocDeployment
        if ($result) {
            Write-LogMessage "Teardown completed successfully" -Level INFO
        }
        else {
            Write-LogMessage "Teardown completed with warnings" -Level WARN
        }
        
        Show-DeploymentStatus
    }
    
    "Deploy" {
        # Install IIS if needed
        if (-not $SkipIISCheck) {
            $iisOk = Install-IISIfNeeded
            if (-not $iisOk) {
                Write-LogMessage "IIS installation failed or requires restart" -Level ERROR
                exit 1
            }
        }
        
        # Verify appcmd is available
        if (-not (Test-AppCmdAvailable)) {
            Write-LogMessage "appcmd.exe not found - IIS may not be properly installed" -Level ERROR
            exit 1
        }
        
        # Set IIS permissions on content folder
        $permOk = Set-IISContentPermissions -Path $ContentPath
        if (-not $permOk) {
            Write-LogMessage "Failed to set IIS permissions on content folder" -Level WARN
        }
        
        # Create app pool
        $poolOk = New-AutoDocAppPool
        if (-not $poolOk) {
            Write-LogMessage "Failed to create application pool" -Level ERROR
            exit 1
        }
        
        # Create virtual application
        $appOk = New-AutoDocVirtualApp
        if (-not $appOk) {
            Write-LogMessage "Failed to create virtual application" -Level ERROR
            exit 1
        }
        
        # Configure MIME types
        Set-AutoDocMimeTypes | Out-Null
        
        # Configure Windows Authentication (disable anonymous, enable Windows auth)
        Set-AutoDocWindowsAuthentication | Out-Null
        
        Write-LogMessage "Deployment completed successfully" -Level INFO
        Show-DeploymentStatus
        
        Write-Host ""
        Write-Host "AutoDoc is now accessible at: http://localhost/$AppName/" -ForegroundColor Green
        Write-Host "(Windows Authentication enabled - domain users will authenticate automatically)" -ForegroundColor Gray
        Write-Host ""
    }
    
    "Redeploy" {
        Write-LogMessage "Starting full redeployment..." -Level INFO
        
        # Teardown first
        if (Test-IISInstalled) {
            Remove-AutoDocDeployment | Out-Null
        }
        
        # Clean generated files if requested
        if ($CleanGeneratedFiles) {
            Clear-AutoDocGeneratedFiles | Out-Null
        }
        
        # Now deploy
        # Install IIS if needed
        if (-not $SkipIISCheck) {
            $iisOk = Install-IISIfNeeded
            if (-not $iisOk) {
                Write-LogMessage "IIS installation failed or requires restart" -Level ERROR
                exit 1
            }
        }
        
        # Verify appcmd is available
        if (-not (Test-AppCmdAvailable)) {
            Write-LogMessage "appcmd.exe not found - IIS may not be properly installed" -Level ERROR
            exit 1
        }
        
        # Set IIS permissions on content folder
        $permOk = Set-IISContentPermissions -Path $ContentPath
        if (-not $permOk) {
            Write-LogMessage "Failed to set IIS permissions on content folder" -Level WARN
        }
        
        # Create app pool
        $poolOk = New-AutoDocAppPool
        if (-not $poolOk) {
            Write-LogMessage "Failed to create application pool" -Level ERROR
            exit 1
        }
        
        # Create virtual application
        $appOk = New-AutoDocVirtualApp
        if (-not $appOk) {
            Write-LogMessage "Failed to create virtual application" -Level ERROR
            exit 1
        }
        
        # Configure MIME types
        Set-AutoDocMimeTypes | Out-Null
        
        # Configure Windows Authentication (disable anonymous, enable Windows auth)
        Set-AutoDocWindowsAuthentication | Out-Null
        
        Write-LogMessage "Redeployment completed successfully" -Level INFO
        Show-DeploymentStatus
        
        Write-Host ""
        Write-Host "AutoDoc is now accessible at: http://localhost/$AppName/" -ForegroundColor Green
        Write-Host "(Windows Authentication enabled - domain users will authenticate automatically)" -ForegroundColor Gray
        Write-Host ""
        Start-Process "http://localhost/$AppName/"
    }
}

#endregion Main Execution
